<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\About;

/**
 * Wraps Google\Service\Drive\Resource\About.
 */
class AboutResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
    ];

    /**
     * Gets information about the user, the user's Drive, and system capabilities.
     * For more information, see [Return user
     * info](https://developers.google.com/workspace/drive/api/guides/user-info).
     * Required: The `fields` parameter must be set. To return the exact fields you
     * need, see [Return specific
     * fields](https://developers.google.com/workspace/drive/api/guides/fields-
     * parameter). (about.get)
     *
     * @param  array  $optParams  Optional parameters.
     * @return About
     *
     * @throws GoogleWorkspaceException
     */
    public function get($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
