<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\AccessProposal;
use Google\Service\Drive\ListAccessProposalsResponse;
use Google\Service\Drive\ResolveAccessProposalRequest;

/**
 * Wraps Google\Service\Drive\Resource\Accessproposals.
 */
class AccessproposalsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
        'listAccessproposals' => 'GET',
        'resolve' => 'POST',
    ];

    /**
     * Retrieves an access proposal by ID. For more information, see [Manage pending
     * access
     * proposals](https://developers.google.com/workspace/drive/api/guides/pending-
     * access). (accessproposals.get)
     *
     * @param  string  $fileId  Required. The ID of the item the request is on.
     * @param  string  $proposalId  Required. The ID of the access proposal to resolve.
     * @param  array  $optParams  Optional parameters.
     * @return AccessProposal
     *
     * @throws GoogleWorkspaceException
     */
    public function get($fileId, $proposalId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * List the access proposals on a file. For more information, see [Manage
     * pending access
     * proposals](https://developers.google.com/workspace/drive/api/guides/pending-
     * access). Note: Only approvers are able to list access proposals on a file. If
     * the user isn't an approver, a 403 error is returned.
     * (accessproposals.listAccessproposals)
     *
     * @param  string  $fileId  Required. The ID of the item the request is on.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Optional. The number of results per page.
     * @opt_param string pageToken Optional. The continuation token on the list of
     * access requests.
     *
     * @return ListAccessProposalsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listAccessproposals($fileId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Approves or denies an access proposal. For more information, see [Manage
     * pending access
     * proposals](https://developers.google.com/workspace/drive/api/guides/pending-
     * access). (accessproposals.resolve)
     *
     * @param  string  $fileId  Required. The ID of the item the request is on.
     * @param  string  $proposalId  Required. The ID of the access proposal to resolve.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function resolve($fileId, $proposalId, ResolveAccessProposalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
