<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\Approval;
use Google\Service\Drive\ApprovalList;
use Google\Service\Drive\ApproveApprovalRequest;
use Google\Service\Drive\CancelApprovalRequest;
use Google\Service\Drive\CommentApprovalRequest;
use Google\Service\Drive\DeclineApprovalRequest;
use Google\Service\Drive\ReassignApprovalRequest;
use Google\Service\Drive\StartApprovalRequest;

/**
 * Wraps Google\Service\Drive\Resource\Approvals.
 */
class ApprovalsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'approve' => 'POST',
        'cancel' => 'POST',
        'comment' => 'POST',
        'decline' => 'POST',
        'get' => 'GET',
        'listApprovals' => 'GET',
        'reassign' => 'POST',
        'start' => 'POST',
    ];

    /**
     * Approves an approval. For more information, see [Manage approvals](https://de
     * velopers.google.com/workspace/drive/api/guides/approvals). This is used to
     * update the ReviewerResponse of the requesting user with a Response of
     * `APPROVED`. If this is the last required reviewer response, this also
     * completes the approval and sets the approval Status to `APPROVED`.
     * (approvals.approve)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  string  $approvalId  Required. The ID of the approval to approve.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function approve($fileId, $approvalId, ApproveApprovalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Cancels an approval. For more information, see [Manage approvals](https://dev
     * elopers.google.com/workspace/drive/api/guides/approvals). Updates the
     * approval Status to `CANCELLED`. This can be called by any user with the
     * `writer` permission on the file while the approval Status is `IN_PROGRESS`.
     * (approvals.cancel)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  string  $approvalId  Required. The ID of the approval to cancel.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function cancel($fileId, $approvalId, CancelApprovalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Comments on an approval. For more information, see [Manage approvals](https:/
     * /developers.google.com/workspace/drive/api/guides/approvals). This sends a
     * notification to both the initiator and the reviewers. Additionally, a message
     * is also added to the approval activity log. (approvals.comment)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  string  $approvalId  Required. The ID of the approval to comment on.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function comment($fileId, $approvalId, CommentApprovalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Declines an approval. For more information, see [Manage approvals](https://de
     * velopers.google.com/workspace/drive/api/guides/approvals). This is used to
     * update the ReviewerResponse of the requesting user with a Response of
     * `DECLINED`. This also completes the approval and sets the approval Status to
     * `DECLINED`. (approvals.decline)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  string  $approvalId  Required. The ID of the approval to decline.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function decline($fileId, $approvalId, DeclineApprovalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets an approval by ID. For more information, see [Manage approvals](https://
     * developers.google.com/workspace/drive/api/guides/approvals). (approvals.get)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  string  $approvalId  Required. The ID of the approval.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function get($fileId, $approvalId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the approvals on a file. For more information, see [Manage approvals](h
     * ttps://developers.google.com/workspace/drive/api/guides/approvals). By
     * default, this method returns a minimal response that may not include the
     * items array. To retrieve approval details, you must explicitly specify the
     * fields you want using the `fields` query parameter. To return the exact
     * fields you need, see [Return specific
     * fields](https://developers.google.com/workspace/drive/api/guides/fields-
     * parameter). (approvals.listApprovals)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize The maximum number of approvals to return. When not
     * set, at most 100 approvals are returned.
     * @opt_param string pageToken The token for continuing a previous list request
     * on the next page. This should be set to the value of `nextPageToken` from a
     * previous response.
     *
     * @return ApprovalList
     *
     * @throws GoogleWorkspaceException
     */
    public function listApprovals($fileId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Reassigns the reviewers on an approval. For more information, see [Manage app
     * rovals](https://developers.google.com/workspace/drive/api/guides/approvals).
     * Adds or replaces reviewers in the ReviewerResponse of the approval. This can
     * be called by any user with the `writer` permission on the file while the
     * approval Status is `IN_PROGRESS` and the Response for the reviewer being
     * reassigned is `NO_RESPONSE`. A user with the `reader` permission can only
     * reassign an approval that's assigned to themselves. Removing a reviewer isn't
     * allowed. (approvals.reassign)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is on.
     * @param  string  $approvalId  Required. The ID of the approval to reassign.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function reassign($fileId, $approvalId, ReassignApprovalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Starts an approval on a file. For more information, see [Manage approvals](ht
     * tps://developers.google.com/workspace/drive/api/guides/approvals).
     * (approvals.start)
     *
     * @param  string  $fileId  Required. The ID of the file that the approval is
     *                          created on.
     * @param  array  $optParams  Optional parameters.
     * @return Approval
     *
     * @throws GoogleWorkspaceException
     */
    public function start($fileId, StartApprovalRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
