<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\App;
use Google\Service\Drive\AppList;

/**
 * Wraps Google\Service\Drive\Resource\Apps.
 */
class AppsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
        'listApps' => 'GET',
    ];

    /**
     * Gets a specific app. For more information, see [Return user
     * info](https://developers.google.com/workspace/drive/api/guides/user-info).
     * (apps.get)
     *
     * @param  string  $appId  The ID of the app.
     * @param  array  $optParams  Optional parameters.
     * @return App
     *
     * @throws GoogleWorkspaceException
     */
    public function get($appId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists a user's installed apps. For more information, see [Return user
     * info](https://developers.google.com/workspace/drive/api/guides/user-info).
     * (apps.listApps)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string appFilterExtensions A comma-separated list of file
     * extensions to limit returned results. All results within the given app query
     * scope which can open any of the given file extensions are included in the
     * response. If `appFilterMimeTypes` are provided as well, the result is a union
     * of the two resulting app lists.
     * @opt_param string appFilterMimeTypes A comma-separated list of file
     * extensions to limit returned results. All results within the given app query
     * scope which can open any of the given MIME types will be included in the
     * response. If `appFilterExtensions` are provided as well, the result is a
     * union of the two resulting app lists.
     * @opt_param string languageCode A language or locale code, as defined by BCP
     * 47, with some extensions from Unicode's LDML format
     * (http://www.unicode.org/reports/tr35/).
     *
     * @return AppList
     *
     * @throws GoogleWorkspaceException
     */
    public function listApps($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
