<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\ChangeList;
use Google\Service\Drive\Channel;
use Google\Service\Drive\StartPageToken;

/**
 * Wraps Google\Service\Drive\Resource\Changes.
 */
class ChangesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'getStartPageToken' => 'GET',
        'listChanges' => 'GET',
        'watch' => 'POST',
    ];

    /**
     * Gets the starting pageToken for listing future changes. For more information,
     * see [Retrieve
     * changes](https://developers.google.com/workspace/drive/api/guides/manage-
     * changes). (changes.getStartPageToken)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string driveId The ID of the shared drive for which the starting
     * pageToken for listing future changes from that shared drive will be returned.
     * @opt_param bool supportsAllDrives Whether the requesting application supports
     * both My Drives and shared drives.
     * @opt_param bool supportsTeamDrives Deprecated: Use `supportsAllDrives`
     * instead.
     * @opt_param string teamDriveId Deprecated: Use `driveId` instead.
     *
     * @return StartPageToken
     *
     * @throws GoogleWorkspaceException
     */
    public function getStartPageToken($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the changes for a user or shared drive. For more information, see
     * [Retrieve
     * changes](https://developers.google.com/workspace/drive/api/guides/manage-
     * changes). (changes.listChanges)
     *
     * @param  string  $pageToken  The token for continuing a previous list request on
     *                             the next page. This should be set to the value of 'nextPageToken' from the
     *                             previous response or to the response from the getStartPageToken method.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string driveId The shared drive from which changes will be
     * returned. If specified the change IDs will be reflective of the shared drive;
     * use the combined drive ID and change ID as an identifier.
     * @opt_param bool includeCorpusRemovals Whether changes should include the file
     * resource if the file is still accessible by the user at the time of the
     * request, even when a file was removed from the list of changes and there will
     * be no further change entries for this file.
     * @opt_param bool includeItemsFromAllDrives Whether both My Drive and shared
     * drive items should be included in results.
     * @opt_param string includeLabels A comma-separated list of IDs of labels to
     * include in the `labelInfo` part of the response.
     * @opt_param string includePermissionsForView Specifies which additional view's
     * permissions to include in the response. Only 'published' is supported.
     * @opt_param bool includeRemoved Whether to include changes indicating that
     * items have been removed from the list of changes, for example by deletion or
     * loss of access.
     * @opt_param bool includeTeamDriveItems Deprecated: Use
     * `includeItemsFromAllDrives` instead.
     * @opt_param int pageSize The maximum number of changes to return. The service
     * may return fewer than this value. If unspecified, at most 100 changes will be
     * returned. The maximum value is 1000; values above 1000 will be coerced to
     * 1000.
     * @opt_param bool restrictToMyDrive Whether to restrict the results to changes
     * inside the My Drive hierarchy. This omits changes to files such as those in
     * the Application Data folder or shared files which have not been added to My
     * Drive.
     * @opt_param string spaces A comma-separated list of spaces to query within the
     * corpora. Supported values are 'drive' and 'appDataFolder'.
     * @opt_param bool supportsAllDrives Whether the requesting application supports
     * both My Drives and shared drives.
     * @opt_param bool supportsTeamDrives Deprecated: Use `supportsAllDrives`
     * instead.
     * @opt_param string teamDriveId Deprecated: Use `driveId` instead.
     *
     * @return ChangeList
     *
     * @throws GoogleWorkspaceException
     */
    public function listChanges($pageToken, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Subscribes to changes for a user. For more information, see [Notifications
     * for resource
     * changes](https://developers.google.com/workspace/drive/api/guides/push).
     * (changes.watch)
     *
     * @param  string  $pageToken  The token for continuing a previous list request on
     *                             the next page. This should be set to the value of 'nextPageToken' from the
     *                             previous response or to the response from the getStartPageToken method.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string driveId The shared drive from which changes will be
     * returned. If specified the change IDs will be reflective of the shared drive;
     * use the combined drive ID and change ID as an identifier.
     * @opt_param bool includeCorpusRemovals Whether changes should include the file
     * resource if the file is still accessible by the user at the time of the
     * request, even when a file was removed from the list of changes and there will
     * be no further change entries for this file.
     * @opt_param bool includeItemsFromAllDrives Whether both My Drive and shared
     * drive items should be included in results.
     * @opt_param string includeLabels A comma-separated list of IDs of labels to
     * include in the `labelInfo` part of the response.
     * @opt_param string includePermissionsForView Specifies which additional view's
     * permissions to include in the response. Only 'published' is supported.
     * @opt_param bool includeRemoved Whether to include changes indicating that
     * items have been removed from the list of changes, for example by deletion or
     * loss of access.
     * @opt_param bool includeTeamDriveItems Deprecated: Use
     * `includeItemsFromAllDrives` instead.
     * @opt_param int pageSize The maximum number of changes to return. The service
     * may return fewer than this value. If unspecified, at most 100 changes will be
     * returned. The maximum value is 1000; values above 1000 will be coerced to
     * 1000.
     * @opt_param bool restrictToMyDrive Whether to restrict the results to changes
     * inside the My Drive hierarchy. This omits changes to files such as those in
     * the Application Data folder or shared files which have not been added to My
     * Drive.
     * @opt_param string spaces A comma-separated list of spaces to query within the
     * corpora. Supported values are 'drive' and 'appDataFolder'.
     * @opt_param bool supportsAllDrives Whether the requesting application supports
     * both My Drives and shared drives.
     * @opt_param bool supportsTeamDrives Deprecated: Use `supportsAllDrives`
     * instead.
     * @opt_param string teamDriveId Deprecated: Use `driveId` instead.
     *
     * @return Channel
     *
     * @throws GoogleWorkspaceException
     */
    public function watch($pageToken, Channel $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
