<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\Comment;
use Google\Service\Drive\CommentList;

/**
 * Wraps Google\Service\Drive\Resource\Comments.
 */
class CommentsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listComments' => 'GET',
        'update' => 'PATCH',
    ];

    /**
     * Creates a comment on a file. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). Required: The `fields` parameter must be set. To return the exact
     * fields you need, see [Return specific
     * fields](https://developers.google.com/workspace/drive/api/guides/fields-
     * parameter). (comments.create)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  array  $optParams  Optional parameters.
     * @return Comment
     *
     * @throws GoogleWorkspaceException
     */
    public function create($fileId, Comment $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a comment. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). (comments.delete)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($fileId, $commentId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets a comment by ID. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). Required: The `fields` parameter must be set. To return the exact
     * fields you need, see [Return specific
     * fields](https://developers.google.com/workspace/drive/api/guides/fields-
     * parameter). (comments.get)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeDeleted Whether to return deleted comments. Deleted
     * comments will not include their original content.
     *
     * @return Comment
     *
     * @throws GoogleWorkspaceException
     */
    public function get($fileId, $commentId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists a file's comments. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). Required: The `fields` parameter must be set. To return the exact
     * fields you need, see [Return specific
     * fields](https://developers.google.com/workspace/drive/api/guides/fields-
     * parameter). (comments.listComments)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeDeleted Whether to include deleted comments. Deleted
     * comments will not include their original content.
     * @opt_param int pageSize The maximum number of comments to return. The service
     * may return fewer than this value. If unspecified, at most 20 comments will be
     * returned. The maximum value is 100; values above 100 will be coerced to 100.
     * @opt_param string pageToken The token for continuing a previous list request
     * on the next page. This should be set to the value of 'nextPageToken' from the
     * previous response.
     * @opt_param string startModifiedTime The minimum value of 'modifiedTime' for
     * the result comments (RFC 3339 date-time).
     *
     * @return CommentList
     *
     * @throws GoogleWorkspaceException
     */
    public function listComments($fileId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a comment with patch semantics. For more information, see [Manage
     * comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). Required: The `fields` parameter must be set. To return the exact
     * fields you need, see [Return specific
     * fields](https://developers.google.com/workspace/drive/api/guides/fields-
     * parameter). (comments.update)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  array  $optParams  Optional parameters.
     * @return Comment
     *
     * @throws GoogleWorkspaceException
     */
    public function update($fileId, $commentId, Comment $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
