<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\Drive;
use Google\Service\Drive\DriveList;

/**
 * Wraps Google\Service\Drive\Resource\Drives.
 */
class DrivesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'hide' => 'POST',
        'listDrives' => 'GET',
        'unhide' => 'POST',
        'update' => 'PATCH',
    ];

    /**
     * Creates a shared drive. For more information, see [Manage shared
     * drives](https://developers.google.com/workspace/drive/api/guides/manage-
     * shareddrives). (drives.create)
     *
     * @param  string  $requestId  Required. An ID, such as a random UUID, which
     *                             uniquely identifies this user's request for idempotent creation of a shared
     *                             drive. A repeated request by the same user and with the same request ID will
     *                             avoid creating duplicates by attempting to create the same shared drive. If
     *                             the shared drive already exists a 409 error will be returned.
     * @param  array  $optParams  Optional parameters.
     * @return Drive
     *
     * @throws GoogleWorkspaceException
     */
    public function create($requestId, Drive $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Permanently deletes a shared drive for which the user is an `organizer`. The
     * shared drive cannot contain any untrashed items. For more information, see
     * [Manage shared
     * drives](https://developers.google.com/workspace/drive/api/guides/manage-
     * shareddrives). (drives.delete)
     *
     * @param  string  $driveId  The ID of the shared drive.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool allowItemDeletion Whether any items inside the shared drive
     * should also be deleted. This option is only supported when
     * `useDomainAdminAccess` is also set to `true`.
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then the requester will be granted access if
     * they are an administrator of the domain to which the shared drive belongs.
     *
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($driveId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets a shared drive's metadata by ID. For more information, see [Manage
     * shared
     * drives](https://developers.google.com/workspace/drive/api/guides/manage-
     * shareddrives). (drives.get)
     *
     * @param  string  $driveId  The ID of the shared drive.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then the requester will be granted access if
     * they are an administrator of the domain to which the shared drive belongs.
     *
     * @return Drive
     *
     * @throws GoogleWorkspaceException
     */
    public function get($driveId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Hides a shared drive from the default view. For more information, see [Manage
     * shared
     * drives](https://developers.google.com/workspace/drive/api/guides/manage-
     * shareddrives). (drives.hide)
     *
     * @param  string  $driveId  The ID of the shared drive.
     * @param  array  $optParams  Optional parameters.
     * @return Drive
     *
     * @throws GoogleWorkspaceException
     */
    public function hide($driveId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the user's shared drives. This method accepts the `q` parameter, which
     * is a search query combining one or more search terms. For more information,
     * see the [Search for shared
     * drives](https://developers.google.com/workspace/drive/api/guides/search-
     * shareddrives) guide. (drives.listDrives)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize The maximum number of shared drives to return. The
     * service may return fewer than this value. If unspecified, at most 10 shared
     * drives will be returned. The maximum value is 100; values above 100 will be
     * coerced to 100.
     * @opt_param string pageToken Page token for shared drives.
     * @opt_param string q Query string for searching shared drives.
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then all shared drives of the domain in which
     * the requester is an administrator are returned.
     *
     * @return DriveList
     *
     * @throws GoogleWorkspaceException
     */
    public function listDrives($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Restores a shared drive to the default view. For more information, see
     * [Manage shared
     * drives](https://developers.google.com/workspace/drive/api/guides/manage-
     * shareddrives). (drives.unhide)
     *
     * @param  string  $driveId  The ID of the shared drive.
     * @param  array  $optParams  Optional parameters.
     * @return Drive
     *
     * @throws GoogleWorkspaceException
     */
    public function unhide($driveId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates the metadata for a shared drive. For more information, see [Manage
     * shared
     * drives](https://developers.google.com/workspace/drive/api/guides/manage-
     * shareddrives). (drives.update)
     *
     * @param  string  $driveId  The ID of the shared drive.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then the requester will be granted access if
     * they are an administrator of the domain to which the shared drive belongs.
     *
     * @return Drive
     *
     * @throws GoogleWorkspaceException
     */
    public function update($driveId, Drive $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
