<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\Operation;

/**
 * Wraps Google\Service\Drive\Resource\Operations.
 */
class OperationsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
    ];

    /**
     * Gets the latest state of a long-running operation. Clients can use this
     * method to poll the operation result at intervals as recommended by the API
     * service. (operations.get)
     *
     * @param  string  $name  The name of the operation resource.
     * @param  array  $optParams  Optional parameters.
     * @return Operation
     *
     * @throws GoogleWorkspaceException
     */
    public function get($name, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
