<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\Reply;
use Google\Service\Drive\ReplyList;

/**
 * Wraps Google\Service\Drive\Resource\Replies.
 */
class RepliesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listReplies' => 'GET',
        'update' => 'PATCH',
    ];

    /**
     * Creates a reply to a comment. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). (replies.create)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  array  $optParams  Optional parameters.
     * @return Reply
     *
     * @throws GoogleWorkspaceException
     */
    public function create($fileId, $commentId, Reply $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a reply. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). (replies.delete)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  string  $replyId  The ID of the reply.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($fileId, $commentId, $replyId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets a reply by ID. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). (replies.get)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  string  $replyId  The ID of the reply.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeDeleted Whether to return deleted replies. Deleted
     * replies don't include their original content.
     *
     * @return Reply
     *
     * @throws GoogleWorkspaceException
     */
    public function get($fileId, $commentId, $replyId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists a comment's replies. For more information, see [Manage comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). (replies.listReplies)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeDeleted Whether to include deleted replies. Deleted
     * replies don't include their original content.
     * @opt_param int pageSize The maximum number of replies to return. The service
     * may return fewer than this value. If unspecified, at most 20 replies will be
     * returned. The maximum value is 100; values above 100 will be coerced to 100.
     * @opt_param string pageToken The token for continuing a previous list request
     * on the next page. This should be set to the value of `nextPageToken` from the
     * previous response.
     *
     * @return ReplyList
     *
     * @throws GoogleWorkspaceException
     */
    public function listReplies($fileId, $commentId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a reply with patch semantics. For more information, see [Manage
     * comments and
     * replies](https://developers.google.com/workspace/drive/api/guides/manage-
     * comments). (replies.update)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $commentId  The ID of the comment.
     * @param  string  $replyId  The ID of the reply.
     * @param  array  $optParams  Optional parameters.
     * @return Reply
     *
     * @throws GoogleWorkspaceException
     */
    public function update($fileId, $commentId, $replyId, Reply $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
