<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\Revision;
use Google\Service\Drive\RevisionList;

/**
 * Wraps Google\Service\Drive\Resource\Revisions.
 */
class RevisionsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'listRevisions' => 'GET',
        'update' => 'PATCH',
    ];

    /**
     * Permanently deletes a file version. You can only delete revisions for files
     * with binary content in Google Drive, like images or videos. Revisions for
     * other files, like Google Docs or Sheets, and the last remaining file version
     * can't be deleted. For more information, see [Manage file
     * revisions](https://developers.google.com/drive/api/guides/manage-revisions).
     * (revisions.delete)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $revisionId  The ID of the revision.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($fileId, $revisionId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets a revision's metadata or content by ID. For more information, see
     * [Manage file
     * revisions](https://developers.google.com/workspace/drive/api/guides/manage-
     * revisions). (revisions.get)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $revisionId  The ID of the revision.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool acknowledgeAbuse Whether the user is acknowledging the risk
     * of downloading known malware or other abusive files. This is only applicable
     * when the `alt` parameter is set to `media` and the user is the owner of the
     * file or an organizer of the shared drive in which the file resides.
     *
     * @return Revision
     *
     * @throws GoogleWorkspaceException
     */
    public function get($fileId, $revisionId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists a file's revisions. For more information, see [Manage file
     * revisions](https://developers.google.com/workspace/drive/api/guides/manage-
     * revisions). **Important:** The list of revisions returned by this method
     * might be incomplete for files with a large revision history, including
     * frequently edited Google Docs, Sheets, and Slides. Older revisions might be
     * omitted from the response, meaning the first revision returned may not be the
     * oldest existing revision. The revision history visible in the Workspace
     * editor user interface might be more complete than the list returned by the
     * API. (revisions.listRevisions)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize The maximum number of revisions to return. The
     * service may return fewer than this value. If unspecified, at most 200
     * revisions will be returned. The maximum value is 1000; values above 1000 will
     * be coerced to 1000.
     * @opt_param string pageToken The token for continuing a previous list request
     * on the next page. This should be set to the value of 'nextPageToken' from the
     * previous response.
     *
     * @return RevisionList
     *
     * @throws GoogleWorkspaceException
     */
    public function listRevisions($fileId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a revision with patch semantics. For more information, see [Manage
     * file
     * revisions](https://developers.google.com/workspace/drive/api/guides/manage-
     * revisions). (revisions.update)
     *
     * @param  string  $fileId  The ID of the file.
     * @param  string  $revisionId  The ID of the revision.
     * @param  array  $optParams  Optional parameters.
     * @return Revision
     *
     * @throws GoogleWorkspaceException
     */
    public function update($fileId, $revisionId, Revision $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
