<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Drive;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Drive\TeamDrive;
use Google\Service\Drive\TeamDriveList;

/**
 * Wraps Google\Service\Drive\Resource\Teamdrives.
 */
class TeamdrivesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listTeamdrives' => 'GET',
        'update' => 'PATCH',
    ];

    /**
     * Deprecated: Use `drives.create` instead. (teamdrives.create)
     *
     * @param  string  $requestId  Required. An ID, such as a random UUID, which
     *                             uniquely identifies this user's request for idempotent creation of a Team
     *                             Drive. A repeated request by the same user and with the same request ID will
     *                             avoid creating duplicates by attempting to create the same Team Drive. If the
     *                             Team Drive already exists a 409 error will be returned.
     * @param  array  $optParams  Optional parameters.
     * @return TeamDrive
     *
     * @throws GoogleWorkspaceException
     */
    public function create($requestId, TeamDrive $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deprecated: Use `drives.delete` instead. (teamdrives.delete)
     *
     * @param  string  $teamDriveId  The ID of the Team Drive
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($teamDriveId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deprecated: Use `drives.get` instead. (teamdrives.get)
     *
     * @param  string  $teamDriveId  The ID of the Team Drive
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then the requester will be granted access if
     * they are an administrator of the domain to which the Team Drive belongs.
     *
     * @return TeamDrive
     *
     * @throws GoogleWorkspaceException
     */
    public function get($teamDriveId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deprecated: Use `drives.list` instead. (teamdrives.listTeamdrives)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of Team Drives to return.
     * @opt_param string pageToken Page token for Team Drives.
     * @opt_param string q Query string for searching Team Drives.
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then all Team Drives of the domain in which
     * the requester is an administrator are returned.
     *
     * @return TeamDriveList
     *
     * @throws GoogleWorkspaceException
     */
    public function listTeamdrives($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deprecated: Use `drives.update` instead. (teamdrives.update)
     *
     * @param  string  $teamDriveId  The ID of the Team Drive
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool useDomainAdminAccess Issue the request as a domain
     * administrator; if set to true, then the requester will be granted access if
     * they are an administrator of the domain to which the Team Drive belongs.
     *
     * @return TeamDrive
     *
     * @throws GoogleWorkspaceException
     */
    public function update($teamDriveId, TeamDrive $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
