<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Asp;
use Google\Service\Directory\Asps;

/**
 * Wraps Google\Service\Directory\Resource\Asps.
 */
class AspsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'listAsps' => 'GET',
    ];

    /**
     * Deletes an ASP issued by a user. (asps.delete)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  int  $codeId  The unique ID of the ASP to be deleted.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userKey, $codeId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets information about an ASP issued by a user. (asps.get)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  int  $codeId  The unique ID of the ASP.
     * @param  array  $optParams  Optional parameters.
     * @return Asp
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userKey, $codeId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the ASPs issued by a user. (asps.listAsps)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return Asps
     *
     * @throws GoogleWorkspaceException
     */
    public function listAsps($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
