<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Channel;

/**
 * Wraps Google\Service\Directory\Resource\Channels.
 */
class ChannelsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'stop' => 'POST',
    ];

    /**
     * Stops watching resources through this channel. (channels.stop)
     *
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function stop(Channel $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
