<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\ChromeOsDevice;
use Google\Service\Directory\ChromeOsDeviceAction;
use Google\Service\Directory\ChromeOsDevices;
use Google\Service\Directory\ChromeOsMoveDevicesToOu;

/**
 * Wraps Google\Service\Directory\Resource\Chromeosdevices.
 */
class ChromeosdevicesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'action' => 'POST',
        'get' => 'GET',
        'listChromeosdevices' => 'GET',
        'moveDevicesToOu' => 'POST',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Use [BatchChangeChromeOsDeviceStatus](https://developers.google.com/workspace
     * /admin/directory/reference/rest/v1/customer.devices.chromeos/batchChangeStatu
     * s) instead. Takes an action that affects a Chrome OS Device. This includes
     * deprovisioning, disabling, and re-enabling devices. *Warning:* *
     * Deprovisioning a device will stop device policy syncing and remove device-
     * level printers. After a device is deprovisioned, it must be wiped before it
     * can be re-enrolled. * Lost or stolen devices should use the disable action. *
     * Re-enabling a disabled device will consume a device license. If you do not
     * have sufficient licenses available when completing the re-enable action, you
     * will receive an error. For more information about deprovisioning and
     * disabling devices, visit the [help
     * center](https://support.google.com/chrome/a/answer/3523633).
     * (chromeosdevices.action)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $resourceId  The unique ID of the device. The `resourceId`s are
     *                              returned in the response from the [chromeosdevices.list](https://developers.g
     *                              oogle.com/workspace/admin/directory/v1/reference/chromeosdevices/list)
     *                              method.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function action($customerId, $resourceId, ChromeOsDeviceAction $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a Chrome OS device's properties. (chromeosdevices.get)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $deviceId  The unique ID of the device. The `deviceId`s are
     *                            returned in the response from the [chromeosdevices.list](https://developers.g
     *                            oogle.com/workspace/admin/directory/v1/reference/chromeosdevices/list)
     *                            method.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string projection Determines whether the response contains the
     * full list of properties or only a subset.
     *
     * @return ChromeOsDevice
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customerId, $deviceId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a paginated list of Chrome OS devices within an account.
     * (chromeosdevices.listChromeosdevices)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeChildOrgunits Return devices from all child orgunits,
     * as well as the specified org unit. If this is set to true, 'orgUnitPath' must
     * be provided.
     * @opt_param int maxResults Maximum number of results to return. Value should
     * not exceed 300.
     * @opt_param string orderBy Device property to use for sorting results.
     * @opt_param string orgUnitPath The full path of the organizational unit (minus
     * the leading `/`) or its unique ID.
     * @opt_param string pageToken The `pageToken` query parameter is used to
     * request the next page of query results. The follow-on request's `pageToken`
     * query parameter is the `nextPageToken` from your previous response.
     * @opt_param string projection Determines whether the response contains the
     * full list of properties or only a subset.
     * @opt_param string query Search string in the format given at [List query
     * operators](https://developers.google.com/workspace/admin/directory/v1/list-
     * query-operators).
     * @opt_param string sortOrder Whether to return results in ascending or
     * descending order. Must be used with the `orderBy` parameter.
     *
     * @return ChromeOsDevices
     *
     * @throws GoogleWorkspaceException
     */
    public function listChromeosdevices($customerId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Moves or inserts multiple Chrome OS devices to an organizational unit. You
     * can move up to 50 devices at once. (chromeosdevices.moveDevicesToOu)
     *
     * @param  string  $customerId  Immutable. ID of the Google Workspace account
     * @param  string  $orgUnitPath  Full path of the target organizational unit or its
     *                               ID
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function moveDevicesToOu($customerId, $orgUnitPath, ChromeOsMoveDevicesToOu $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a device's updatable properties, such as `annotatedUser`,
     * `annotatedLocation`, `notes`, `orgUnitPath`, or `annotatedAssetId`. This
     * method supports [patch semantics](https://developers.google.com/workspace/adm
     * in/directory/v1/guides/performance#patch). (chromeosdevices.patch)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $deviceId  The unique ID of the device. The `deviceId`s are
     *                            returned in the response from the [chromeosdevices.list](https://developers.g
     *                            oogle.com/workspace/admin/v1/reference/chromeosdevices/list) method.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string projection Determines whether the response contains the
     * full list of properties or only a subset.
     *
     * @return ChromeOsDevice
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customerId, $deviceId, ChromeOsDevice $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a device's updatable properties, such as `annotatedUser`,
     * `annotatedLocation`, `notes`, `orgUnitPath`, or `annotatedAssetId`.
     * (chromeosdevices.update)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $deviceId  The unique ID of the device. The `deviceId`s are
     *                            returned in the response from the [chromeosdevices.list](https://developers.g
     *                            oogle.com/workspace/admin/v1/reference/chromeosdevices/list) method.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string projection Determines whether the response contains the
     * full list of properties or only a subset.
     *
     * @return ChromeOsDevice
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customerId, $deviceId, ChromeOsDevice $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
