<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Customer;

/**
 * Wraps Google\Service\Directory\Resource\Customers.
 */
class CustomersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Retrieves a customer. (customers.get)
     *
     * @param  string  $customerKey  Id of the customer to be retrieved
     * @param  array  $optParams  Optional parameters.
     * @return Customer
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customerKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patches a customer. (customers.patch)
     *
     * @param  string  $customerKey  Id of the customer to be updated
     * @param  array  $optParams  Optional parameters.
     * @return Customer
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customerKey, Customer $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a customer. (customers.update)
     *
     * @param  string  $customerKey  Id of the customer to be updated
     * @param  array  $optParams  Optional parameters.
     * @return Customer
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customerKey, Customer $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
