<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\DirectoryChromeosdevicesCommand;

/**
 * Wraps Google\Service\Directory\Resource\CustomerDevicesChromeosCommands.
 */
class CustomerDevicesChromeosCommandsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
    ];

    /**
     * Gets command data a specific command issued to the device. (commands.get)
     *
     * @param  string  $customerId  Immutable. ID of the Google Workspace account.
     * @param  string  $deviceId  Immutable. ID of Chrome OS Device.
     * @param  string  $commandId  Immutable. ID of Chrome OS Device Command.
     * @param  array  $optParams  Optional parameters.
     * @return DirectoryChromeosdevicesCommand
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customerId, $deviceId, $commandId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
