<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\BatchChangeChromeOsDeviceStatusRequest;
use Google\Service\Directory\BatchChangeChromeOsDeviceStatusResponse;
use Google\Service\Directory\CountChromeOsDevicesResponse;
use Google\Service\Directory\DirectoryChromeosdevicesIssueCommandRequest;
use Google\Service\Directory\DirectoryChromeosdevicesIssueCommandResponse;

/**
 * Wraps Google\Service\Directory\Resource\CustomerDevicesChromeos.
 */
class CustomerDevicesChromeosResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'batchChangeStatus' => 'POST',
        'countChromeOsDevices' => 'GET',
        'issueCommand' => 'POST',
    ];

    /**
     * Changes the status of a batch of ChromeOS devices. For more information about
     * changing a ChromeOS device state [Repair, repurpose, or retire ChromeOS
     * devices](https://support.google.com/chrome/a/answer/3523633).
     * (chromeos.batchChangeStatus)
     *
     * @param  string  $customerId  Required. Immutable ID of the Google Workspace
     *                              account.
     * @param  array  $optParams  Optional parameters.
     * @return BatchChangeChromeOsDeviceStatusResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function batchChangeStatus($customerId, BatchChangeChromeOsDeviceStatusRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Counts ChromeOS devices matching the request. (chromeos.countChromeOsDevices)
     *
     * @param  string  $customerId  Required. Immutable ID of the Google Workspace
     *                              account.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string filter Optional. Search string in the format given at [List
     * query
     * operators](https://developers.google.com/workspace/admin/directory/v1/list-
     * query-operators).
     * @opt_param bool includeChildOrgunits Optional. Return devices from all child
     * orgunits, as well as the specified org unit. If this is set to true,
     * 'orgUnitPath' must be provided.
     * @opt_param string orgUnitPath Optional. The full path of the organizational
     * unit (minus the leading `/`) or its unique ID.
     *
     * @return CountChromeOsDevicesResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function countChromeOsDevices($customerId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Issues a command for the device to execute. (chromeos.issueCommand)
     *
     * @param  string  $customerId  Immutable. ID of the Google Workspace account.
     * @param  string  $deviceId  Immutable. ID of Chrome OS Device.
     * @param  array  $optParams  Optional parameters.
     * @return DirectoryChromeosdevicesIssueCommandResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function issueCommand($customerId, $deviceId, DirectoryChromeosdevicesIssueCommandRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
