<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\AdminEmpty;
use Google\Service\Directory\BatchCreatePrintersRequest;
use Google\Service\Directory\BatchCreatePrintersResponse;
use Google\Service\Directory\BatchDeletePrintersRequest;
use Google\Service\Directory\BatchDeletePrintersResponse;
use Google\Service\Directory\ListPrinterModelsResponse;
use Google\Service\Directory\ListPrintersResponse;
use Google\Service\Directory\Printer;

/**
 * Wraps Google\Service\Directory\Resource\CustomersChromePrinters.
 */
class CustomersChromePrintersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'batchCreatePrinters' => 'POST',
        'batchDeletePrinters' => 'POST',
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listCustomersChromePrinters' => 'GET',
        'listPrinterModels' => 'GET',
        'patch' => 'PATCH',
    ];

    /**
     * Creates printers under given Organization Unit.
     * (printers.batchCreatePrinters)
     *
     * @param  string  $parent  Required. The name of the customer. Format:
     *                          customers/{customer_id}
     * @param  array  $optParams  Optional parameters.
     * @return BatchCreatePrintersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function batchCreatePrinters($parent, BatchCreatePrintersRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes printers in batch. (printers.batchDeletePrinters)
     *
     * @param  string  $parent  Required. The name of the customer. Format:
     *                          customers/{customer_id}
     * @param  array  $optParams  Optional parameters.
     * @return BatchDeletePrintersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function batchDeletePrinters($parent, BatchDeletePrintersRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a printer under given Organization Unit. (printers.create)
     *
     * @param  string  $parent  Required. The name of the customer. Format:
     *                          customers/{customer_id}
     * @param  array  $optParams  Optional parameters.
     * @return Printer
     *
     * @throws GoogleWorkspaceException
     */
    public function create($parent, Printer $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a `Printer`. (printers.delete)
     *
     * @param  string  $name  Required. The name of the printer to be updated. Format:
     *                        customers/{customer_id}/chrome/printers/{printer_id}
     * @param  array  $optParams  Optional parameters.
     * @return AdminEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($name, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a `Printer` resource (printer's config). (printers.get)
     *
     * @param  string  $name  Required. The name of the printer to retrieve. Format:
     *                        customers/{customer_id}/chrome/printers/{printer_id}
     * @param  array  $optParams  Optional parameters.
     * @return Printer
     *
     * @throws GoogleWorkspaceException
     */
    public function get($name, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * List printers configs. (printers.listCustomersChromePrinters)
     *
     * @param  string  $parent  Required. The name of the customer who owns this
     *                          collection of printers. Format: customers/{customer_id}
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string filter Search query. Search syntax is shared between this
     * api and Admin Console printers pages.
     * @opt_param string orderBy The order to sort results by. Must be one of
     * display_name, description, make_and_model, or create_time. Default order is
     * ascending, but descending order can be returned by appending "desc" to the
     * order_by field. For instance, "description desc" will return the printers
     * sorted by description in descending order.
     * @opt_param string orgUnitId Organization Unit that we want to list the
     * printers for. When org_unit is not present in the request then all printers
     * of the customer are returned (or filtered). When org_unit is present in the
     * request then only printers available to this OU will be returned (owned or
     * inherited). You may see if printer is owned or inherited for this OU by
     * looking at Printer.org_unit_id.
     * @opt_param int pageSize The maximum number of objects to return. The service
     * may return fewer than this value.
     * @opt_param string pageToken A page token, received from a previous call.
     *
     * @return ListPrintersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCustomersChromePrinters($parent, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the supported printer models. (printers.listPrinterModels)
     *
     * @param  string  $parent  Required. The name of the customer who owns this
     *                          collection of printers. Format: customers/{customer_id}
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string filter Filer to list only models by a given manufacturer in
     * format: "manufacturer:Brother". Search syntax is shared between this api and
     * Admin Console printers pages.
     * @opt_param int pageSize The maximum number of objects to return. The service
     * may return fewer than this value.
     * @opt_param string pageToken A page token, received from a previous call.
     *
     * @return ListPrinterModelsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listPrinterModels($parent, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a `Printer` resource. (printers.patch)
     *
     * @param  string  $name  Identifier. The resource name of the Printer object, in
     *                        the format customers/{customer-id}/printers/{printer-id} (During printer
     *                        creation leave empty)
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string clearMask The list of fields to be cleared. Note, some of
     * the fields are read only and cannot be updated. Values for not specified
     * fields will be patched.
     * @opt_param string updateMask The list of fields to be updated. Note, some of
     * the fields are read only and cannot be updated. Values for not specified
     * fields will be patched.
     *
     * @return Printer
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($name, Printer $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
