<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\AdminEmpty;
use Google\Service\Directory\BatchCreatePrintServersRequest;
use Google\Service\Directory\BatchCreatePrintServersResponse;
use Google\Service\Directory\BatchDeletePrintServersRequest;
use Google\Service\Directory\BatchDeletePrintServersResponse;
use Google\Service\Directory\ListPrintServersResponse;
use Google\Service\Directory\PrintServer;

/**
 * Wraps Google\Service\Directory\Resource\CustomersChromePrintServers.
 */
class CustomersChromePrintServersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'batchCreatePrintServers' => 'POST',
        'batchDeletePrintServers' => 'POST',
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listCustomersChromePrintServers' => 'GET',
        'patch' => 'PATCH',
    ];

    /**
     * Creates multiple print servers. (printServers.batchCreatePrintServers)
     *
     * @param  string  $parent  Required. The [unique ID](https://developers.google.com
     *                          /workspace/admin/directory/reference/rest/v1/customers) of the customer's
     *                          Google Workspace account. Format: `customers/{id}`
     * @param  array  $optParams  Optional parameters.
     * @return BatchCreatePrintServersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function batchCreatePrintServers($parent, BatchCreatePrintServersRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes multiple print servers. (printServers.batchDeletePrintServers)
     *
     * @param  string  $parent  Required. The [unique ID](https://developers.google.com
     *                          /workspace/admin/directory/reference/rest/v1/customers) of the customer's
     *                          Google Workspace account. Format: `customers/{customer.id}`
     * @param  array  $optParams  Optional parameters.
     * @return BatchDeletePrintServersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function batchDeletePrintServers($parent, BatchDeletePrintServersRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a print server. (printServers.create)
     *
     * @param  string  $parent  Required. The [unique ID](https://developers.google.com
     *                          /workspace/admin/directory/reference/rest/v1/customers) of the customer's
     *                          Google Workspace account. Format: `customers/{id}`
     * @param  array  $optParams  Optional parameters.
     * @return PrintServer
     *
     * @throws GoogleWorkspaceException
     */
    public function create($parent, PrintServer $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a print server. (printServers.delete)
     *
     * @param  string  $name  Required. The name of the print server to be deleted.
     *                        Format: `customers/{customer.id}/chrome/printServers/{print_server.id}`
     * @param  array  $optParams  Optional parameters.
     * @return AdminEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($name, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a print server's configuration. (printServers.get)
     *
     * @param  string  $name  Required. The [unique ID](https://developers.google.com/w
     *                        orkspace/admin/directory/reference/rest/v1/customers) of the customer's
     *                        Google Workspace account. Format: `customers/{id}`
     * @param  array  $optParams  Optional parameters.
     * @return PrintServer
     *
     * @throws GoogleWorkspaceException
     */
    public function get($name, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists print server configurations.
     * (printServers.listCustomersChromePrintServers)
     *
     * @param  string  $parent  Required. The [unique ID](https://developers.google.com
     *                          /workspace/admin/directory/reference/rest/v1/customers) of the customer's
     *                          Google Workspace account. Format: `customers/{id}`
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string filter Search query in [Common Expression Language
     * syntax](https://github.com/google/cel-spec). Supported filters are
     * `display_name`, `description`, and `uri`. Example:
     * `printServer.displayName=='marketing-queue'`.
     * @opt_param string orderBy Sort order for results. Supported values are
     * `display_name`, `description`, or `create_time`. Default order is ascending,
     * but descending order can be returned by appending "desc" to the `order_by`
     * field. For instance, `orderBy=='description desc'` returns the print servers
     * sorted by description in descending order.
     * @opt_param string orgUnitId If `org_unit_id` is present in the request, only
     * print servers owned or inherited by the organizational unit (OU) are
     * returned. If the `PrintServer` resource's `org_unit_id` matches the one in
     * the request, the OU owns the server. If `org_unit_id` is not specified in the
     * request, all print servers are returned or filtered against.
     * @opt_param int pageSize The maximum number of objects to return (default
     * `100`, max `100`). The service might return fewer than this value.
     * @opt_param string pageToken A generated token to paginate results (the
     * `next_page_token` from a previous call).
     *
     * @return ListPrintServersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCustomersChromePrintServers($parent, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a print server's configuration. (printServers.patch)
     *
     * @param  string  $name  Identifier. Resource name of the print server. Leave
     *                        empty when creating. Format:
     *                        `customers/{customer.id}/printServers/{print_server.id}`
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string updateMask The list of fields to update. Some fields are
     * read-only and cannot be updated. Values for unspecified fields are patched.
     *
     * @return PrintServer
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($name, PrintServer $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
