<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Domains;
use Google\Service\Directory\Domains2;

/**
 * Wraps Google\Service\Directory\Resource\Domains.
 */
class DomainsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listDomains' => 'GET',
    ];

    /**
     * Deletes a domain of the customer. (domains.delete)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  string  $domainName  Name of domain to be deleted
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $domainName, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a domain of the customer. (domains.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  string  $domainName  Name of domain to be retrieved
     * @param  array  $optParams  Optional parameters.
     * @return Domains
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $domainName, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Inserts a domain of the customer. (domains.insert)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  array  $optParams  Optional parameters.
     * @return Domains
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, Domains $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the domains of the customer. (domains.listDomains)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  array  $optParams  Optional parameters.
     * @return Domains2
     *
     * @throws GoogleWorkspaceException
     */
    public function listDomains($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
