<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\DomainAlias;
use Google\Service\Directory\DomainAliases;

/**
 * Wraps Google\Service\Directory\Resource\DomainAliases.
 */
class DomainAliasesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listDomainAliases' => 'GET',
    ];

    /**
     * Deletes a domain Alias of the customer. (domainAliases.delete)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  string  $domainAliasName  Name of domain alias to be retrieved.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $domainAliasName, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a domain alias of the customer. (domainAliases.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  string  $domainAliasName  Name of domain alias to be retrieved.
     * @param  array  $optParams  Optional parameters.
     * @return DomainAlias
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $domainAliasName, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Inserts a domain alias of the customer. (domainAliases.insert)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  array  $optParams  Optional parameters.
     * @return DomainAlias
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, DomainAlias $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the domain aliases of the customer. (domainAliases.listDomainAliases)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string parentDomainName Name of the parent domain for which domain
     * aliases are to be fetched.
     *
     * @return DomainAliases
     *
     * @throws GoogleWorkspaceException
     */
    public function listDomainAliases($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
