<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Alias;
use Google\Service\Directory\Aliases;

/**
 * Wraps Google\Service\Directory\Resource\GroupsAliases.
 */
class GroupsAliasesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'insert' => 'POST',
        'listGroupsAliases' => 'GET',
    ];

    /**
     * Removes an alias. (aliases.delete)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  string  $alias  The alias to be removed
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($groupKey, $alias, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Adds an alias for the group. (aliases.insert)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return Alias
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($groupKey, Alias $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists all aliases for a group. (aliases.listGroupsAliases)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return Aliases
     *
     * @throws GoogleWorkspaceException
     */
    public function listGroupsAliases($groupKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
