<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Group;
use Google\Service\Directory\Groups;

/**
 * Wraps Google\Service\Directory\Resource\Groups.
 */
class GroupsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listGroups' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Deletes a group. (groups.delete)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($groupKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a group's properties. (groups.get)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return Group
     *
     * @throws GoogleWorkspaceException
     */
    public function get($groupKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a group. (groups.insert)
     *
     * @param  array  $optParams  Optional parameters.
     * @return Group
     *
     * @throws GoogleWorkspaceException
     */
    public function insert(Group $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves all groups of a domain or of a user given a userKey (paginated).
     * (groups.listGroups)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string customer The unique ID for the customer's Google Workspace
     * account. In case of a multi-domain account, to fetch all groups for a
     * customer, use this field instead of `domain`. You can also use the
     * `my_customer` alias to represent your account's `customerId`. The
     * `customerId` is also returned as part of the [Users](https://developers.googl
     * e.com/workspace/admin/directory/v1/reference/users) resource. You must
     * provide either the `customer` or the `domain` parameter.
     * @opt_param string domain The domain name. Use this field to get groups from
     * only one domain. To return all domains for a customer account, use the
     * `customer` query parameter instead.
     * @opt_param int maxResults Maximum number of results to return. Max allowed
     * value is 200.
     * @opt_param string orderBy Column to use for sorting results
     * @opt_param string pageToken Token to specify next page in the list
     * @opt_param string query Query string search. Contains one or more search
     * clauses, each with a field, operator, and value. For complete documentation,
     * go to [Search for groups](https://developers.google.com/workspace/admin/direc
     * tory/v1/guides/search-groups).
     * @opt_param string sortOrder Whether to return results in ascending or
     * descending order. Only of use when orderBy is also used
     * @opt_param string userKey Email or immutable ID of the user if only those
     * groups are to be listed, the given user is a member of. If it's an ID, it
     * should match with the ID of the user object. Cannot be used with the
     * `customer` parameter.
     *
     * @return Groups
     *
     * @throws GoogleWorkspaceException
     */
    public function listGroups($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a group's properties. This method supports [patch semantics](https://
     * developers.google.com/workspace/admin/directory/v1/guides/performance#patch).
     * (groups.patch)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return Group
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($groupKey, Group $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a group's properties. (groups.update)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return Group
     *
     * @throws GoogleWorkspaceException
     */
    public function update($groupKey, Group $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
