<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Member;
use Google\Service\Directory\Members;
use Google\Service\Directory\MembersHasMember;

/**
 * Wraps Google\Service\Directory\Resource\Members.
 */
class MembersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'hasMember' => 'GET',
        'insert' => 'POST',
        'listMembers' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Removes a member from a group. (members.delete)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  string  $memberKey  Identifies the group member in the API request. A
     *                             group member can be a user or another group. The value can be the member's
     *                             (group or user) primary email address, alias, or unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($groupKey, $memberKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a group member's properties. (members.get)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  string  $memberKey  Identifies the group member in the API request. A
     *                             group member can be a user or another group. The value can be the member's
     *                             (group or user) primary email address, alias, or unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return Member
     *
     * @throws GoogleWorkspaceException
     */
    public function get($groupKey, $memberKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Checks whether the given user is a member of the group. Membership can be
     * direct or nested, but if nested, the `memberKey` and `groupKey` must be
     * entities in the same domain or an `Invalid input` error is returned. To check
     * for nested memberships that include entities outside of the group's domain,
     * use the [`checkTransitiveMembership()`](https://cloud.google.com/identity/doc
     * s/reference/rest/v1/groups.memberships/checkTransitiveMembership) method in
     * the Cloud Identity Groups API. (members.hasMember)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  string  $memberKey  Identifies the user member in the API request. The
     *                             value can be the user's primary email address, alias, or unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return MembersHasMember
     *
     * @throws GoogleWorkspaceException
     */
    public function hasMember($groupKey, $memberKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Adds a user to the specified group. (members.insert)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     * @return Member
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($groupKey, Member $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a paginated list of all members in a group. This method times out
     * after 60 minutes. For more information, see [Troubleshoot error codes](https:
     * //developers.google.com/workspace/admin/directory/v1/guides/troubleshoot-
     * error-codes). (members.listMembers)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeDerivedMembership Whether to list indirect
     * memberships. Default: false.
     * @opt_param int maxResults Maximum number of results to return. Max allowed
     * value is 200.
     * @opt_param string pageToken Token to specify next page in the list.
     * @opt_param string roles The `roles` query parameter allows you to retrieve
     * group members by role. Allowed values are `OWNER`, `MANAGER`, and `MEMBER`.
     *
     * @return Members
     *
     * @throws GoogleWorkspaceException
     */
    public function listMembers($groupKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates the membership properties of a user in the specified group. This
     * method supports [patch semantics](https://developers.google.com/workspace/adm
     * in/directory/v1/guides/performance#patch). (members.patch)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  string  $memberKey  Identifies the group member in the API request. A
     *                             group member can be a user or another group. The value can be the member's
     *                             (group or user) primary email address, alias, or unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return Member
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($groupKey, $memberKey, Member $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates the membership of a user in the specified group. (members.update)
     *
     * @param  string  $groupKey  Identifies the group in the API request. The value
     *                            can be the group's email address, group alias, or the unique group ID.
     * @param  string  $memberKey  Identifies the group member in the API request. A
     *                             group member can be a user or another group. The value can be the member's
     *                             (group or user) primary email address, alias, or unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return Member
     *
     * @throws GoogleWorkspaceException
     */
    public function update($groupKey, $memberKey, Member $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
