<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\OrgUnit;
use Google\Service\Directory\OrgUnits;

/**
 * Wraps Google\Service\Directory\Resource\Orgunits.
 */
class OrgunitsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listOrgunits' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Removes an organizational unit. (orgunits.delete)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $orgUnitPath  The full path of the organizational unit (minus
     *                               the leading `/`) or its unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customerId, $orgUnitPath, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves an organizational unit. (orgunits.get)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $orgUnitPath  The full path of the organizational unit (minus
     *                               the leading `/`) or its unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return OrgUnit
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customerId, $orgUnitPath, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Adds an organizational unit. (orgunits.insert)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  array  $optParams  Optional parameters.
     * @return OrgUnit
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customerId, OrgUnit $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a list of all organizational units for an account.
     * (orgunits.listOrgunits)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string orgUnitPath The full path to the organizational unit or its
     * unique ID. Returns the children of the specified organizational unit.
     * @opt_param string type Whether to return all sub-organizations or just
     * immediate children.
     *
     * @return OrgUnits
     *
     * @throws GoogleWorkspaceException
     */
    public function listOrgunits($customerId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates an organizational unit. This method supports [patch semantics](https:
     * //developers.google.com/workspace/admin/directory/v1/guides/performance#patch
     * ) (orgunits.patch)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $orgUnitPath  The full path of the organizational unit (minus
     *                               the leading `/`) or its unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return OrgUnit
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customerId, $orgUnitPath, OrgUnit $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates an organizational unit. (orgunits.update)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. As an account administrator, you can also use the `my_customer`
     *                              alias to represent your account's `customerId`. The `customerId` is also
     *                              returned as part of the [Users resource](https://developers.google.com/worksp
     *                              ace/admin/directory/v1/reference/users).
     * @param  string  $orgUnitPath  The full path of the organizational unit (minus
     *                               the leading `/`) or its unique ID.
     * @param  array  $optParams  Optional parameters.
     * @return OrgUnit
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customerId, $orgUnitPath, OrgUnit $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
