<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Privileges;

/**
 * Wraps Google\Service\Directory\Resource\Privileges.
 */
class PrivilegesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'listPrivileges' => 'GET',
    ];

    /**
     * Retrieves a paginated list of all privileges for a customer.
     * (privileges.listPrivileges)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  array  $optParams  Optional parameters.
     * @return Privileges
     *
     * @throws GoogleWorkspaceException
     */
    public function listPrivileges($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
