<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Building;
use Google\Service\Directory\Buildings;

/**
 * Wraps Google\Service\Directory\Resource\ResourcesBuildings.
 */
class ResourcesBuildingsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listResourcesBuildings' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Deletes a building. (buildings.delete)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $buildingId  The id of the building to delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $buildingId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a building. (buildings.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $buildingId  The unique ID of the building to retrieve.
     * @param  array  $optParams  Optional parameters.
     * @return Building
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $buildingId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Inserts a building. (buildings.insert)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string coordinatesSource Source from which Building.coordinates
     * are derived.
     *
     * @return Building
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, Building $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a list of buildings for an account.
     * (buildings.listResourcesBuildings)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of results to return.
     * @opt_param string pageToken Token to specify the next page in the list.
     *
     * @return Buildings
     *
     * @throws GoogleWorkspaceException
     */
    public function listResourcesBuildings($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patches a building. (buildings.patch)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $buildingId  The id of the building to update.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string coordinatesSource Source from which Building.coordinates
     * are derived.
     *
     * @return Building
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customer, $buildingId, Building $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a building. (buildings.update)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $buildingId  The id of the building to update.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string coordinatesSource Source from which Building.coordinates
     * are derived.
     *
     * @return Building
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customer, $buildingId, Building $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
