<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\CalendarResource;
use Google\Service\Directory\CalendarResources;

/**
 * Wraps Google\Service\Directory\Resource\ResourcesCalendars.
 */
class ResourcesCalendarsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listResourcesCalendars' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Deletes a calendar resource. (calendars.delete)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $calendarResourceId  The unique ID of the calendar resource to
     *                                      delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $calendarResourceId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a calendar resource. (calendars.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $calendarResourceId  The unique ID of the calendar resource to
     *                                      retrieve.
     * @param  array  $optParams  Optional parameters.
     * @return CalendarResource
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $calendarResourceId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Inserts a calendar resource. (calendars.insert)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  array  $optParams  Optional parameters.
     * @return CalendarResource
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, CalendarResource $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a list of calendar resources for an account.
     * (calendars.listResourcesCalendars)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of results to return.
     * @opt_param string orderBy Field(s) to sort results by in either ascending or
     * descending order. Supported fields include `resourceId`, `resourceName`,
     * `capacity`, `buildingId`, and `floorName`. If no order is specified, defaults
     * to ascending. Should be of the form "field [asc|desc], field [asc|desc],
     * ...". For example `buildingId, capacity desc` would return results sorted
     * first by `buildingId` in ascending order then by `capacity` in descending
     * order.
     * @opt_param string pageToken Token to specify the next page in the list.
     * @opt_param string query String query used to filter results. Contains one or
     * more search clauses, each with a field, operator, and value. A field can be
     * any of supported fields and operators can be any of supported operations.
     * Operators include '=' for exact match, '!=' for mismatch and ':' for prefix
     * match or HAS match where applicable. For prefix match, the value should
     * always be followed by a *. Logical operators NOT and AND are supported (in
     * this order of precedence). Supported fields include `generatedResourceName`,
     * `name`, `buildingId`, `floor_name`, `capacity`,
     * `featureInstances.feature.name`, `resourceEmail`, `resourceCategory`. For
     * example `buildingId=US-NYC-9TH AND featureInstances.feature.name:Phone`.
     *
     * @return CalendarResources
     *
     * @throws GoogleWorkspaceException
     */
    public function listResourcesCalendars($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patches a calendar resource. (calendars.patch)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $calendarResourceId  The unique ID of the calendar resource to
     *                                      update.
     * @param  array  $optParams  Optional parameters.
     * @return CalendarResource
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customer, $calendarResourceId, CalendarResource $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a calendar resource. This method supports patch semantics, meaning
     * you only need to include the fields you wish to update. Fields that are not
     * present in the request will be preserved. (calendars.update)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $calendarResourceId  The unique ID of the calendar resource to
     *                                      update.
     * @param  array  $optParams  Optional parameters.
     * @return CalendarResource
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customer, $calendarResourceId, CalendarResource $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
