<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Feature;
use Google\Service\Directory\FeatureRename;
use Google\Service\Directory\Features;

/**
 * Wraps Google\Service\Directory\Resource\ResourcesFeatures.
 */
class ResourcesFeaturesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listResourcesFeatures' => 'GET',
        'patch' => 'PATCH',
        'rename' => 'POST',
        'update' => 'PUT',
    ];

    /**
     * Deletes a feature. (features.delete)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $featureKey  The unique ID of the feature to delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $featureKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a feature. (features.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $featureKey  The unique ID of the feature to retrieve.
     * @param  array  $optParams  Optional parameters.
     * @return Feature
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $featureKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Inserts a feature. (features.insert)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  array  $optParams  Optional parameters.
     * @return Feature
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, Feature $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a list of features for an account. (features.listResourcesFeatures)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of results to return.
     * @opt_param string pageToken Token to specify the next page in the list.
     *
     * @return Features
     *
     * @throws GoogleWorkspaceException
     */
    public function listResourcesFeatures($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patches a feature. (features.patch)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $featureKey  The unique ID of the feature to update.
     * @param  array  $optParams  Optional parameters.
     * @return Feature
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customer, $featureKey, Feature $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Renames a feature. (features.rename)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $oldName  The unique ID of the feature to rename.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function rename($customer, $oldName, FeatureRename $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a feature. (features.update)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. As an account administrator, you can also use the `my_customer`
     *                            alias to represent your account's customer ID.
     * @param  string  $featureKey  The unique ID of the feature to update.
     * @param  array  $optParams  Optional parameters.
     * @return Feature
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customer, $featureKey, Feature $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
