<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Role;
use Google\Service\Directory\Roles;

/**
 * Wraps Google\Service\Directory\Resource\Roles.
 */
class RolesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listRoles' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Deletes a role. (roles.delete)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  string  $roleId  Immutable ID of the role.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $roleId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a role. (roles.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  string  $roleId  Immutable ID of the role.
     * @param  array  $optParams  Optional parameters.
     * @return Role
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $roleId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a role. (roles.insert)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  array  $optParams  Optional parameters.
     * @return Role
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, Role $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a paginated list of all the roles in a domain. (roles.listRoles)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of results to return.
     * @opt_param string pageToken Token to specify the next page in the list.
     *
     * @return Roles
     *
     * @throws GoogleWorkspaceException
     */
    public function listRoles($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patches a role. (roles.patch)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  string  $roleId  Immutable ID of the role.
     * @param  array  $optParams  Optional parameters.
     * @return Role
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customer, $roleId, Role $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a role. (roles.update)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  string  $roleId  Immutable ID of the role.
     * @param  array  $optParams  Optional parameters.
     * @return Role
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customer, $roleId, Role $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
