<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\RoleAssignment;
use Google\Service\Directory\RoleAssignments;

/**
 * Wraps Google\Service\Directory\Resource\RoleAssignments.
 */
class RoleAssignmentsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listRoleAssignments' => 'GET',
    ];

    /**
     * Deletes a role assignment. (roleAssignments.delete)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  string  $roleAssignmentId  Immutable ID of the role assignment.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customer, $roleAssignmentId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a role assignment. (roleAssignments.get)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  string  $roleAssignmentId  Immutable ID of the role assignment.
     * @param  array  $optParams  Optional parameters.
     * @return RoleAssignment
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customer, $roleAssignmentId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a role assignment. (roleAssignments.insert)
     *
     * @param  string  $customer  Immutable ID of the Google Workspace account.
     * @param  array  $optParams  Optional parameters.
     * @return RoleAssignment
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customer, RoleAssignment $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a paginated list of all roleAssignments.
     * (roleAssignments.listRoleAssignments)
     *
     * @param  string  $customer  The unique ID for the customer's Google Workspace
     *                            account. In case of a multi-domain account, to fetch all groups for a
     *                            customer, use this field instead of `domain`. You can also use the
     *                            `my_customer` alias to represent your account's `customerId`. The
     *                            `customerId` is also returned as part of the [Users](https://developers.googl
     *                            e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                            provide either the `customer` or the `domain` parameter.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeIndirectRoleAssignments When set to `true`, fetches
     * indirect role assignments (i.e. role assignment via a group) as well as
     * direct ones. Defaults to `false`. You must specify `user_key` or the indirect
     * role assignments will not be included.
     * @opt_param int maxResults Maximum number of results to return.
     * @opt_param string pageToken Token to specify the next page in the list.
     * @opt_param string roleId Immutable ID of a role. If included in the request,
     * returns only role assignments containing this role ID.
     * @opt_param string userKey The primary email address, alias email address, or
     * unique user or group ID. If included in the request, returns role assignments
     * only for this user or group.
     *
     * @return RoleAssignments
     *
     * @throws GoogleWorkspaceException
     */
    public function listRoleAssignments($customer, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
