<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Schema;
use Google\Service\Directory\Schemas;

/**
 * Wraps Google\Service\Directory\Resource\Schemas.
 */
class SchemasResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listSchemas' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Deletes a schema. (schemas.delete)
     *
     * @param  string  $customerId  Immutable ID of the Google Workspace account.
     * @param  string  $schemaKey  Name or immutable ID of the schema.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($customerId, $schemaKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves a schema. (schemas.get)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. In case of a multi-domain account, to fetch all groups for a
     *                              customer, use this field instead of `domain`. You can also use the
     *                              `my_customer` alias to represent your account's `customerId`. The
     *                              `customerId` is also returned as part of the [Users](https://developers.googl
     *                              e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                              provide either the `customer` or the `domain` parameter.
     * @param  string  $schemaKey  Name or immutable ID of the schema.
     * @param  array  $optParams  Optional parameters.
     * @return Schema
     *
     * @throws GoogleWorkspaceException
     */
    public function get($customerId, $schemaKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a schema. (schemas.insert)
     *
     * @param  string  $customerId  Immutable ID of the Google Workspace account.
     * @param  array  $optParams  Optional parameters.
     * @return Schema
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($customerId, Schema $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves all schemas for a customer. (schemas.listSchemas)
     *
     * @param  string  $customerId  The unique ID for the customer's Google Workspace
     *                              account. In case of a multi-domain account, to fetch all groups for a
     *                              customer, use this field instead of `domain`. You can also use the
     *                              `my_customer` alias to represent your account's `customerId`. The
     *                              `customerId` is also returned as part of the [Users](https://developers.googl
     *                              e.com/workspace/admin/directory/v1/reference/users) resource. You must
     *                              provide either the `customer` or the `domain` parameter.
     * @param  array  $optParams  Optional parameters.
     * @return Schemas
     *
     * @throws GoogleWorkspaceException
     */
    public function listSchemas($customerId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patches a schema. (schemas.patch)
     *
     * @param  string  $customerId  Immutable ID of the Google Workspace account.
     * @param  string  $schemaKey  Name or immutable ID of the schema.
     * @param  array  $optParams  Optional parameters.
     * @return Schema
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($customerId, $schemaKey, Schema $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a schema. (schemas.update)
     *
     * @param  string  $customerId  Immutable ID of the Google Workspace account.
     * @param  string  $schemaKey  Name or immutable ID of the schema.
     * @param  array  $optParams  Optional parameters.
     * @return Schema
     *
     * @throws GoogleWorkspaceException
     */
    public function update($customerId, $schemaKey, Schema $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
