<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Token;
use Google\Service\Directory\Tokens;

/**
 * Wraps Google\Service\Directory\Resource\Tokens.
 */
class TokensResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'listTokens' => 'GET',
    ];

    /**
     * Deletes all access tokens issued by a user for an application.
     * (tokens.delete)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  string  $clientId  The Client ID of the application the token is issued
     *                            to.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userKey, $clientId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets information about an access token issued by a user. (tokens.get)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  string  $clientId  The Client ID of the application the token is issued
     *                            to.
     * @param  array  $optParams  Optional parameters.
     * @return Token
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userKey, $clientId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns the set of tokens specified user has issued to 3rd party
     * applications. (tokens.listTokens)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return Tokens
     *
     * @throws GoogleWorkspaceException
     */
    public function listTokens($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
