<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;

/**
 * Wraps Google\Service\Directory\Resource\TwoStepVerification.
 */
class TwoStepVerificationResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'turnOff' => 'POST',
    ];

    /**
     * Turns off 2-Step Verification for user. (twoStepVerification.turnOff)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function turnOff($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
