<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\Alias;
use Google\Service\Directory\Aliases;
use Google\Service\Directory\Channel;

/**
 * Wraps Google\Service\Directory\Resource\UsersAliases.
 */
class UsersAliasesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'insert' => 'POST',
        'listUsersAliases' => 'GET',
        'watch' => 'POST',
    ];

    /**
     * Removes an alias. (aliases.delete)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  string  $alias  The alias to be removed.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userKey, $alias, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Adds an alias. (aliases.insert)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return Alias
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($userKey, Alias $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists all aliases for a user. (aliases.listUsersAliases)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string event Events to watch for.
     *
     * @return Aliases
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersAliases($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Watches for changes in users list. (aliases.watch)
     *
     * @param  string  $userKey  Email or immutable ID of the user
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string event Events to watch for.
     *
     * @return Channel
     *
     * @throws GoogleWorkspaceException
     */
    public function watch($userKey, Channel $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
