<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\UserPhoto;

/**
 * Wraps Google\Service\Directory\Resource\UsersPhotos.
 */
class UsersPhotosResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Removes the user's photo. (photos.delete)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves the user's photo. (photos.get)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return UserPhoto
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Adds a photo for the user. This method supports [patch semantics](https://dev
     * elopers.google.com/workspace/admin/directory/v1/guides/performance#patch).
     * (photos.patch)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return UserPhoto
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($userKey, UserPhoto $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Adds a photo for the user. (photos.update)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return UserPhoto
     *
     * @throws GoogleWorkspaceException
     */
    public function update($userKey, UserPhoto $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
