<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Directory;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Directory\VerificationCodes;

/**
 * Wraps Google\Service\Directory\Resource\VerificationCodes.
 */
class VerificationCodesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'generate' => 'POST',
        'invalidate' => 'POST',
        'listVerificationCodes' => 'GET',
    ];

    /**
     * Generates new backup verification codes for the user.
     * (verificationCodes.generate)
     *
     * @param  string  $userKey  Email or immutable ID of the user
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function generate($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Invalidates the current backup verification codes for the user.
     * (verificationCodes.invalidate)
     *
     * @param  string  $userKey  Email or immutable ID of the user
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function invalidate($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns the current set of valid backup verification codes for the specified
     * user. (verificationCodes.listVerificationCodes)
     *
     * @param  string  $userKey  Identifies the user in the API request. The value can
     *                           be the user's primary email address, alias email address, or unique user ID.
     * @param  array  $optParams  Optional parameters.
     * @return VerificationCodes
     *
     * @throws GoogleWorkspaceException
     */
    public function listVerificationCodes($userKey, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
