<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\ListStudentGroupsResponse;
use Google\Service\Classroom\StudentGroup;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesStudentGroups.
 */
class CoursesStudentGroupsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'listCoursesStudentGroups' => 'GET',
        'patch' => 'PATCH',
    ];

    /**
     * Creates a student group for a course. This method returns the following error
     * codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * create the student group or for access errors. * `NOT_FOUND` if the course
     * does not exist or the requesting user doesn't have access to the course. *
     * `FAILED_PRECONDITION` if creating the student group would exceed the maximum
     * number of student groups per course. (studentGroups.create)
     *
     * @param  string  $courseId  Required. The identifier of the course.
     * @param  array  $optParams  Optional parameters.
     * @return StudentGroup
     *
     * @throws GoogleWorkspaceException
     */
    public function create($courseId, StudentGroup $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a student group. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
     * requested student group or for access errors. * `NOT_FOUND` if the student
     * group does not exist or the user does not have access to the student group.
     * (studentGroups.delete)
     *
     * @param  string  $courseId  Required. The identifier of the course containing the
     *                            student group to delete.
     * @param  string  $id  Required. The identifier of the student group to delete.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($courseId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of groups in a course. This method returns the following error
     * codes: * `NOT_FOUND` if the course does not exist.
     * (studentGroups.listCoursesStudentGroups)
     *
     * @param  string  $courseId  Required. The identifier of the course.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum, which is
     * currently set to 75 items. The server may return fewer than the specified
     * number of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     *
     * @return ListStudentGroupsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCoursesStudentGroups($courseId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates one or more fields in a student group. This method returns the
     * following error codes: * `PERMISSION_DENIED` if the requesting user is not
     * permitted to modify the requested student group or for access errors. *
     * `NOT_FOUND` if the student group does not exist or the user does not have
     * access to the student group. * `INVALID_ARGUMENT` if invalid fields are
     * specified in the update mask or if no update mask is supplied.
     * (studentGroups.patch)
     *
     * @param  string  $courseId  Required. Identifier of the course.
     * @param  string  $id  Required. Identifier of the student group.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string updateMask Required. Mask that identifies which fields on
     * the student group to update. This field is required to do an update. The
     * update fails if invalid fields are specified. The following fields can be
     * specified by teachers: * `title`
     *
     * @return StudentGroup
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($courseId, $id, StudentGroup $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
