<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\ListTopicResponse;
use Google\Service\Classroom\Topic;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesTopics.
 */
class CoursesTopicsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listCoursesTopics' => 'GET',
        'patch' => 'PATCH',
    ];

    /**
     * Creates a topic. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to access the
     * requested course, create a topic in the requested course, or for access
     * errors. * `INVALID_ARGUMENT` if the request is malformed. * `ALREADY_EXISTS`
     * if there exists a topic in the course with the same name. *
     * `FAILED_PRECONDITION` for the following request error: *
     * CourseTopicLimitReached * `NOT_FOUND` if the requested course does not exist.
     * (topics.create)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     * @return Topic
     *
     * @throws GoogleWorkspaceException
     */
    public function create($courseId, Topic $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a topic. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not allowed to delete the
     * requested topic or for access errors. * `FAILED_PRECONDITION` if the
     * requested topic has already been deleted. * `NOT_FOUND` if no course or topic
     * exists with the requested ID. (topics.delete)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  string  $id  Identifier of the topic to delete.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($courseId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a topic. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to access the
     * requested course or topic, or for access errors. * `INVALID_ARGUMENT` if the
     * request is malformed. * `NOT_FOUND` if the requested course or topic does not
     * exist. (topics.get)
     *
     * @param  string  $courseId  Identifier of the course.
     * @param  string  $id  Identifier of the topic.
     * @param  array  $optParams  Optional parameters.
     * @return Topic
     *
     * @throws GoogleWorkspaceException
     */
    public function get($courseId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns the list of topics that the requester is permitted to view. This
     * method returns the following error codes: * `PERMISSION_DENIED` if the
     * requesting user is not permitted to access the requested course or for access
     * errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if
     * the requested course does not exist. (topics.listCoursesTopics)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum. The server may
     * return fewer than the specified number of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     *
     * @return ListTopicResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCoursesTopics($courseId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates one or more fields of a topic. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting developer project did
     * not create the corresponding topic or for access errors. * `INVALID_ARGUMENT`
     * if the request is malformed. * `FAILED_PRECONDITION` if there exists a topic
     * in the course with the same name. * `NOT_FOUND` if the requested course or
     * topic does not exist (topics.patch)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  string  $id  Identifier of the topic.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string updateMask Mask that identifies which fields on the topic
     * to update. This field is required to do an update. The update fails if
     * invalid fields are specified. If a field supports empty values, it can be
     * cleared by specifying it in the update mask and not in the Topic object. If a
     * field that does not support empty values is included in the update mask and
     * not set in the Topic object, an `INVALID_ARGUMENT` error is returned. The
     * following fields may be specified: * `name`
     *
     * @return Topic
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($courseId, $id, Topic $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
