<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\CourseAlias;
use Google\Service\Classroom\ListCourseAliasesResponse;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesAliases.
 */
class CoursesAliasesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'listCoursesAliases' => 'GET',
    ];

    /**
     * Creates an alias for a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to create the
     * alias or for access errors. * `NOT_FOUND` if the course does not exist. *
     * `ALREADY_EXISTS` if the alias already exists. * `FAILED_PRECONDITION` if the
     * alias requested does not make sense for the requesting user or course (for
     * example, if a user not in a domain attempts to access a domain-scoped alias).
     * (aliases.create)
     *
     * @param  string  $courseId  Identifier of the course to alias. This identifier
     *                            can be either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     * @return CourseAlias
     *
     * @throws GoogleWorkspaceException
     */
    public function create($courseId, CourseAlias $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes an alias of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to remove the
     * alias or for access errors. * `NOT_FOUND` if the alias does not exist. *
     * `FAILED_PRECONDITION` if the alias requested does not make sense for the
     * requesting user or course (for example, if a user not in a domain attempts to
     * delete a domain-scoped alias). (aliases.delete)
     *
     * @param  string  $courseId  Identifier of the course whose alias should be
     *                            deleted. This identifier can be either the Classroom-assigned identifier or
     *                            an alias.
     * @param  string  $alias  Alias to delete. This may not be the Classroom-assigned
     *                         identifier.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($courseId, $alias, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of aliases for a course. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * access the course or for access errors. * `NOT_FOUND` if the course does not
     * exist. (aliases.listCoursesAliases)
     *
     * @param  string  $courseId  The identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum. The server may
     * return fewer than the specified number of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     *
     * @return ListCourseAliasesResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCoursesAliases($courseId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
