<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\ListStudentsResponse;
use Google\Service\Classroom\Student;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesStudents.
 */
class CoursesStudentsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listCoursesStudents' => 'GET',
    ];

    /**
     * Adds a user as a student of a course. Domain administrators are permitted to
     * [directly
     * add](https://developers.google.com/workspace/classroom/guides/manage-users)
     * users within their domain as students to courses within their domain.
     * Students are permitted to add themselves to a course using an enrollment
     * code. This method returns the following error codes: * `PERMISSION_DENIED` if
     * the requesting user is not permitted to create students in this course or for
     * access errors. * `NOT_FOUND` if the requested course ID does not exist. *
     * `FAILED_PRECONDITION` if the requested user's account is disabled, for the
     * following request errors: * CourseMemberLimitReached * CourseNotModifiable *
     * UserGroupsMembershipLimitReached * InactiveCourseOwner * `ALREADY_EXISTS` if
     * the user is already a student or teacher in the course. (students.create)
     *
     * @param  string  $courseId  Identifier of the course to create the student in.
     *                            This identifier can be either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string enrollmentCode Enrollment code of the course to create the
     * student in. This code is required if userId corresponds to the requesting
     * user; it may be omitted if the requesting user has administrative permissions
     * to create students for any user.
     *
     * @return Student
     *
     * @throws GoogleWorkspaceException
     */
    public function create($courseId, Student $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a student of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to delete
     * students of this course or for access errors. * `NOT_FOUND` if no student of
     * this course has the requested ID or if the course does not exist.
     * (students.delete)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  string  $userId  Identifier of the student to delete. The identifier can
     *                          be one of the following: * the numeric identifier for the user * the email
     *                          address of the user * the string literal `"me"`, indicating the requesting
     *                          user
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($courseId, $userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a student of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to view
     * students of this course or for access errors. * `NOT_FOUND` if no student of
     * this course has the requested ID or if the course does not exist.
     * (students.get)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  string  $userId  Identifier of the student to return. The identifier can
     *                          be one of the following: * the numeric identifier for the user * the email
     *                          address of the user * the string literal `"me"`, indicating the requesting
     *                          user
     * @param  array  $optParams  Optional parameters.
     * @return Student
     *
     * @throws GoogleWorkspaceException
     */
    public function get($courseId, $userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of students of this course that the requester is permitted to
     * view. This method returns the following error codes: * `NOT_FOUND` if the
     * course does not exist. * `PERMISSION_DENIED` for access errors.
     * (students.listCoursesStudents)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of items to return. The default is 30
     * if unspecified or `0`. The server may return fewer than the specified number
     * of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     *
     * @return ListStudentsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCoursesStudents($courseId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
