<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\ListStudentGroupMembersResponse;
use Google\Service\Classroom\StudentGroupMember;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesStudentGroupsStudentGroupMembers.
 */
class CoursesStudentGroupsStudentGroupMembersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'listCoursesStudentGroupsStudentGroupMembers' => 'GET',
    ];

    /**
     * Creates a student group member for a student group. This method returns the
     * following error codes: * `PERMISSION_DENIED` if the requesting user is not
     * permitted to create the student group or member for access errors. *
     * `NOT_FOUND` if the student group does not exist or the user does not have
     * access to the student group. * `ALREADY_EXISTS` if the student group member
     * already exists. * `FAILED_PRECONDITION` if attempting to add a member to a
     * student group that has reached its member limit. (studentGroupMembers.create)
     *
     * @param  string  $courseId  Required. The identifier of the course.
     * @param  string  $studentGroupId  Required. The identifier of the student group.
     * @param  array  $optParams  Optional parameters.
     * @return StudentGroupMember
     *
     * @throws GoogleWorkspaceException
     */
    public function create($courseId, $studentGroupId, StudentGroupMember $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a student group member. This method returns the following error
     * codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * delete the requested student group member or for access errors. * `NOT_FOUND`
     * if the student group member does not exist or the user does not have access
     * to the student group. (studentGroupMembers.delete)
     *
     * @param  string  $courseId  Required. The identifier of the course containing the
     *                            relevant student group.
     * @param  string  $studentGroupId  Required. The identifier of the student group
     *                                  containing the student group member to delete.
     * @param  string  $userId  Required. The identifier of the student group member to
     *                          delete.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($courseId, $studentGroupId, $userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of students in a group. This method returns the following
     * error codes: * `NOT_FOUND` if the course or student group does not exist.
     * (studentGroupMembers.listCoursesStudentGroupsStudentGroupMembers)
     *
     * @param  string  $courseId  Required. The identifier of the course.
     * @param  string  $studentGroupId  Required. The identifier of the student group.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum. The server may
     * return fewer than the specified number of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     *
     * @return ListStudentGroupMembersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCoursesStudentGroupsStudentGroupMembers($courseId, $studentGroupId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
