<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\ListTeachersResponse;
use Google\Service\Classroom\Teacher;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesTeachers.
 */
class CoursesTeachersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listCoursesTeachers' => 'GET',
    ];

    /**
     * Creates a teacher of a course. Domain administrators are permitted to
     * [directly
     * add](https://developers.google.com/workspace/classroom/guides/manage-users)
     * users within their domain as teachers to courses within their domain. Non-
     * admin users should send an Invitation instead. This method returns the
     * following error codes: * `PERMISSION_DENIED` if the requesting user is not
     * permitted to create teachers in this course or for access errors. *
     * `NOT_FOUND` if the requested course ID does not exist. *
     * `FAILED_PRECONDITION` if the requested user's account is disabled, for the
     * following request errors: * CourseMemberLimitReached * CourseNotModifiable *
     * CourseTeacherLimitReached * UserGroupsMembershipLimitReached *
     * InactiveCourseOwner * `ALREADY_EXISTS` if the user is already a teacher or
     * student in the course. (teachers.create)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     * @return Teacher
     *
     * @throws GoogleWorkspaceException
     */
    public function create($courseId, Teacher $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Removes the specified teacher from the specified course. This method returns
     * the following error codes: * `PERMISSION_DENIED` if the requesting user is
     * not permitted to delete teachers of this course or for access errors. *
     * `NOT_FOUND` if no teacher of this course has the requested ID or if the
     * course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to
     * the primary teacher of this course. * `FAILED_PRECONDITION` if the requested
     * ID belongs to the owner of the course Drive folder. * `FAILED_PRECONDITION`
     * if the course no longer has an active owner. (teachers.delete)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  string  $userId  Identifier of the teacher to delete. The identifier can
     *                          be one of the following: * the numeric identifier for the user * the email
     *                          address of the user * the string literal `"me"`, indicating the requesting
     *                          user
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($courseId, $userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a teacher of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to view
     * teachers of this course or for access errors. * `NOT_FOUND` if no teacher of
     * this course has the requested ID or if the course does not exist.
     * (teachers.get)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  string  $userId  Identifier of the teacher to return. The identifier can
     *                          be one of the following: * the numeric identifier for the user * the email
     *                          address of the user * the string literal `"me"`, indicating the requesting
     *                          user
     * @param  array  $optParams  Optional parameters.
     * @return Teacher
     *
     * @throws GoogleWorkspaceException
     */
    public function get($courseId, $userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of teachers of this course that the requester is permitted to
     * view. This method returns the following error codes: * `NOT_FOUND` if the
     * course does not exist. * `PERMISSION_DENIED` for access errors.
     * (teachers.listCoursesTeachers)
     *
     * @param  string  $courseId  Identifier of the course. This identifier can be
     *                            either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize Maximum number of items to return. The default is 30
     * if unspecified or `0`. The server may return fewer than the specified number
     * of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     *
     * @return ListTeachersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCoursesTeachers($courseId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
