<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\Course;
use Google\Service\Classroom\GradingPeriodSettings;
use Google\Service\Classroom\ListCoursesResponse;

/**
 * Wraps Google\Service\Classroom\Resource\Courses.
 */
class CoursesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'getGradingPeriodSettings' => 'GET',
        'listCourses' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
        'updateGradingPeriodSettings' => 'PATCH',
    ];

    /**
     * Creates a course. The user specified in `ownerId` is the owner of the created
     * course and added as a teacher. A non-admin requesting user can only create a
     * course with themselves as the owner. Domain admins can create courses owned
     * by any user within their domain. This method returns the following error
     * codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * create courses or for access errors. * `NOT_FOUND` if the primary teacher is
     * not a valid user. * `FAILED_PRECONDITION` if the course owner's account is
     * disabled or for the following request errors: * UserCannotOwnCourse *
     * UserGroupsMembershipLimitReached * CourseTitleCannotContainUrl *
     * `ALREADY_EXISTS` if an alias was specified in the `id` and already exists.
     * (courses.create)
     *
     * @param  array  $optParams  Optional parameters.
     * @return Course
     *
     * @throws GoogleWorkspaceException
     */
    public function create(Course $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a course. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
     * requested course or for access errors. * `NOT_FOUND` if no course exists with
     * the requested ID. (courses.delete)
     *
     * @param  string  $id  Identifier of the course to delete. This identifier can be
     *                      either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a course. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to access the
     * requested course or for access errors. * `NOT_FOUND` if no course exists with
     * the requested ID. (courses.get)
     *
     * @param  string  $id  Identifier of the course to return. This identifier can be
     *                      either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     * @return Course
     *
     * @throws GoogleWorkspaceException
     */
    public function get($id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns the grading period settings in a course. This method returns the
     * following error codes: * `PERMISSION_DENIED` if the requesting user isn't
     * permitted to access the grading period settings in the requested course or
     * for access errors. * `NOT_FOUND` if the requested course does not exist.
     * (courses.getGradingPeriodSettings)
     *
     * @param  string  $courseId  Required. The identifier of the course.
     * @param  array  $optParams  Optional parameters.
     * @return GradingPeriodSettings
     *
     * @throws GoogleWorkspaceException
     */
    public function getGradingPeriodSettings($courseId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of courses that the requesting user is permitted to view,
     * restricted to those that match the request. Returned courses are ordered by
     * creation time, with the most recently created coming first. This method
     * returns the following error codes: * `PERMISSION_DENIED` for access errors. *
     * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any
     * users specified in the query arguments do not exist. (courses.listCourses)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string courseStates Restricts returned courses to those in one of
     * the specified states. If unspecified, Courses in any state are returned.
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum. The server may
     * return fewer than the specified number of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param string studentId Restricts returned courses to those having a
     * student with the specified identifier. The identifier can be one of the
     * following: * the numeric identifier for the user * the email address of the
     * user * the string literal `"me"`, indicating the requesting user If
     * specified, `teacher_id` must be empty.
     * @opt_param string teacherId Restricts returned courses to those having a
     * teacher with the specified identifier. The identifier can be one of the
     * following: * the numeric identifier for the user * the email address of the
     * user * the string literal `"me"`, indicating the requesting user If
     * specified, `student_id` must be empty.
     *
     * @return ListCoursesResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listCourses($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates one or more fields in a course. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * modify the requested course or for access errors. * `NOT_FOUND` if no course
     * exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are
     * specified in the update mask or if no update mask is supplied. *
     * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable
     * * InactiveCourseOwner * IneligibleOwner * CourseTitleCannotContainUrl
     * (courses.patch)
     *
     * @param  string  $id  Identifier of the course to update. This identifier can be
     *                      either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string updateMask Mask that identifies which fields on the course
     * to update. This field is required to do an update. The update will fail if
     * invalid fields are specified. The following fields are valid: * `courseState`
     * * `description` * `descriptionHeading` * `name` * `ownerId` * `room` *
     * `section` * `subject` * `learningStandardSettings` * `levels` Note: patches
     * to ownerId are treated as being effective immediately, but in practice it may
     * take some time for the ownership transfer of all affected resources to
     * complete. When set in a query parameter, this field should be specified as
     * `updateMask=,,...`
     *
     * @return Course
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($id, Course $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a course. Note: Unlike other fields, `levels` is not cleared if
     * omitted from the request. The `UpdateCourse` method only modifies `levels` if
     * it is explicitly provided; otherwise, the existing value is preserved. Use
     * the `PatchCourse` method to clear the `levels` field. This method returns the
     * following error codes: * `PERMISSION_DENIED` if the requesting user is not
     * permitted to modify the requested course or for access errors. * `NOT_FOUND`
     * if no course exists with the requested ID. * `FAILED_PRECONDITION` for the
     * following request errors: * CourseNotModifiable * CourseTitleCannotContainUrl
     * (courses.update)
     *
     * @param  string  $id  Identifier of the course to update. This identifier can be
     *                      either the Classroom-assigned identifier or an alias.
     * @param  array  $optParams  Optional parameters.
     * @return Course
     *
     * @throws GoogleWorkspaceException
     */
    public function update($id, Course $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates grading period settings of a course. Individual grading periods can
     * be added, removed, or modified using this method. The requesting user and
     * course owner must be eligible to modify Grading Periods. For details, see
     * [licensing
     * requirements](https://developers.google.com/workspace/classroom/grading-
     * periods/manage-grading-periods#licensing_requirements). This method returns
     * the following error codes: * `PERMISSION_DENIED` if the requesting user is
     * not permitted to modify the grading period settings in a course or for access
     * errors: * UserIneligibleToUpdateGradingPeriodSettings * `INVALID_ARGUMENT` if
     * the request is malformed. * `NOT_FOUND` if the requested course does not
     * exist. (courses.updateGradingPeriodSettings)
     *
     * @param  string  $courseId  Required. The identifier of the course.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string updateMask Mask that identifies which fields in the
     * GradingPeriodSettings to update. The GradingPeriodSettings `grading_periods`
     * list will be fully replaced by the grading periods specified in the update
     * request. For example: * Grading periods included in the list without an ID
     * are considered additions, and a new ID will be assigned when the request is
     * made. * Grading periods that currently exist, but are missing from the
     * request will be considered deletions. * Grading periods with an existing ID
     * and modified data are considered edits. Unmodified data will be left as is. *
     * Grading periods included with an unknown ID will result in an error. The
     * following fields may be specified: * `grading_periods` *
     * `apply_to_existing_coursework`
     *
     * @return GradingPeriodSettings
     *
     * @throws GoogleWorkspaceException
     */
    public function updateGradingPeriodSettings($courseId, GradingPeriodSettings $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
