<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\AddOnAttachmentStudentSubmission;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesPostsAddOnAttachmentsStudentSubmissions.
 */
class CoursesPostsAddOnAttachmentsStudentSubmissionsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
        'patch' => 'PATCH',
    ];

    /**
     * Returns a student submission for an add-on attachment. This method returns
     * the following error codes: * `PERMISSION_DENIED` for access errors. *
     * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the
     * identified resources does not exist. (studentSubmissions.get)
     *
     * @param  string  $courseId  Required. Identifier of the course.
     * @param  string  $postId  Optional. Deprecated, use `item_id` instead.
     * @param  string  $attachmentId  Required. Identifier of the attachment.
     * @param  string  $submissionId  Required. Identifier of the student’s submission.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string itemId Identifier of the `Announcement`, `CourseWork`, or
     * `CourseWorkMaterial` under which the attachment is attached. This field is
     * required, but is not marked as such while we are migrating from post_id.
     *
     * @return AddOnAttachmentStudentSubmission
     *
     * @throws GoogleWorkspaceException
     */
    public function get($courseId, $postId, $attachmentId, $submissionId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates data associated with an add-on attachment submission. Requires the
     * add-on to have been the original creator of the attachment and the attachment
     * to have a positive `max_points` value set. This method returns the following
     * error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if
     * the request is malformed. * `NOT_FOUND` if one of the identified resources
     * does not exist. (studentSubmissions.patch)
     *
     * @param  string  $courseId  Required. Identifier of the course.
     * @param  string  $postId  Optional. Deprecated, use `item_id` instead.
     * @param  string  $attachmentId  Required. Identifier of the attachment.
     * @param  string  $submissionId  Required. Identifier of the student's submission.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string itemId Identifier of the `Announcement`, `CourseWork`, or
     * `CourseWorkMaterial` under which the attachment is attached. This field is
     * required, but is not marked as such while we are migrating from post_id.
     * @opt_param string updateMask Required. Mask that identifies which fields on
     * the attachment to update. The update fails if invalid fields are specified.
     * If a field supports empty values, it can be cleared by specifying it in the
     * update mask and not in the `AddOnAttachmentStudentSubmission` object. The
     * following fields may be specified by teachers: * `points_earned`
     *
     * @return AddOnAttachmentStudentSubmission
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($courseId, $postId, $attachmentId, $submissionId, AddOnAttachmentStudentSubmission $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
