<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\AddOnContext;

/**
 * Wraps Google\Service\Classroom\Resource\CoursesPosts.
 */
class CoursesPostsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'getAddOnContext' => 'GET',
    ];

    /**
     * Gets metadata for Classroom add-ons in the context of a specific post. To
     * maintain the integrity of its own data and permissions model, an add-on
     * should call this to validate query parameters and the requesting user's role
     * whenever the add-on is opened in an
     * [iframe](https://developers.google.com/workspace/classroom/add-ons/get-
     * started/iframes/iframes-overview). This method returns the following error
     * codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the
     * request is malformed. * `NOT_FOUND` if one of the identified resources does
     * not exist. (posts.getAddOnContext)
     *
     * @param  string  $courseId  Required. Identifier of the course.
     * @param  string  $postId  Optional. Deprecated, use `item_id` instead.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string addOnToken Optional. Token that authorizes the request. The
     * token is passed as a query parameter when the user is redirected from
     * Classroom to the add-on's URL. The authorization token is required when
     * neither of the following is true: * The add-on has attachments on the post. *
     * The developer project issuing the request is the same project that created
     * the post.
     * @opt_param string attachmentId Optional. The identifier of the attachment.
     * This field is required for all requests except when the user is in the
     * [Attachment Discovery
     * iframe](https://developers.google.com/workspace/classroom/add-ons/get-
     * started/iframes/attachment-discovery-iframe).
     * @opt_param string itemId Identifier of the `Announcement`, `CourseWork`, or
     * `CourseWorkMaterial` under which the attachment is attached. This field is
     * required, but is not marked as such while we are migrating from post_id.
     *
     * @return AddOnContext
     *
     * @throws GoogleWorkspaceException
     */
    public function getAddOnContext($courseId, $postId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
