<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\ClassroomEmpty;
use Google\Service\Classroom\Invitation;
use Google\Service\Classroom\ListInvitationsResponse;

/**
 * Wraps Google\Service\Classroom\Resource\Invitations.
 */
class InvitationsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'accept' => 'POST',
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listInvitations' => 'GET',
    ];

    /**
     * Accepts an invitation, removing it and adding the invited user to the
     * teachers or students (as appropriate) of the specified course. Only the
     * invited user may accept an invitation. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * accept the requested invitation or for access errors. * `FAILED_PRECONDITION`
     * for the following request errors: * CourseMemberLimitReached *
     * CourseNotModifiable * CourseTeacherLimitReached *
     * UserGroupsMembershipLimitReached * `NOT_FOUND` if no invitation exists with
     * the requested ID. (invitations.accept)
     *
     * @param  string  $id  Identifier of the invitation to accept.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function accept($id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates an invitation. Only one invitation for a user and course may exist at
     * a time. Delete and re-create an invitation to make changes. This method
     * returns the following error codes: * `PERMISSION_DENIED` if the requesting
     * user is not permitted to create invitations for this course or for access
     * errors. * `NOT_FOUND` if the course or the user does not exist. *
     * `FAILED_PRECONDITION`: * if the requested user's account is disabled. * if
     * the user already has this role or a role with greater permissions. * for the
     * following request errors: * IneligibleOwner * `ALREADY_EXISTS` if an
     * invitation for the specified user and course already exists.
     * (invitations.create)
     *
     * @param  array  $optParams  Optional parameters.
     * @return Invitation
     *
     * @throws GoogleWorkspaceException
     */
    public function create(Invitation $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes an invitation. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
     * requested invitation or for access errors. * `NOT_FOUND` if no invitation
     * exists with the requested ID. (invitations.delete)
     *
     * @param  string  $id  Identifier of the invitation to delete.
     * @param  array  $optParams  Optional parameters.
     * @return ClassroomEmpty
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns an invitation. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to view the
     * requested invitation or for access errors. * `NOT_FOUND` if no invitation
     * exists with the requested ID. (invitations.get)
     *
     * @param  string  $id  Identifier of the invitation to return.
     * @param  array  $optParams  Optional parameters.
     * @return Invitation
     *
     * @throws GoogleWorkspaceException
     */
    public function get($id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a list of invitations that the requesting user is permitted to view,
     * restricted to those that match the list request. *Note:* At least one of
     * `user_id` or `course_id` must be supplied. Both fields can be supplied. This
     * method returns the following error codes: * `PERMISSION_DENIED` for access
     * errors. (invitations.listInvitations)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string courseId Restricts returned invitations to those for a
     * course with the specified identifier.
     * @opt_param int pageSize Maximum number of items to return. The default is 500
     * if unspecified or `0`. The server may return fewer than the specified number
     * of results.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param string userId Restricts returned invitations to those for a
     * specific user. The identifier can be one of the following: * the numeric
     * identifier for the user * the email address of the user * the string literal
     * `"me"`, indicating the requesting user
     *
     * @return ListInvitationsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listInvitations($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
