<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Classroom;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Classroom\UserProfile;

/**
 * Wraps Google\Service\Classroom\Resource\UserProfiles.
 */
class UserProfilesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
    ];

    /**
     * Returns a user profile. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to access this
     * user profile, if no profile exists with the requested ID, or for access
     * errors. (userProfiles.get)
     *
     * @param  string  $userId  Identifier of the profile to return. The identifier can
     *                          be one of the following: * the numeric identifier for the user * the email
     *                          address of the user * the string literal `"me"`, indicating the requesting
     *                          user
     * @param  array  $optParams  Optional parameters.
     * @return UserProfile
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
