<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.

namespace BrickServers\GoogleWorkspace\Api;

/**
 * Every resource of the Google Calendar API (Google\Service\Calendar).
 */
class CalendarApi extends ApiService
{
    /**
     * The "acl" resource.
     */
    public function acl(): Calendar\AclResource
    {
        return $this->resource(Calendar\AclResource::class, 'acl');
    }

    /**
     * The "calendarList" resource.
     */
    public function calendarList(): Calendar\CalendarListResource
    {
        return $this->resource(Calendar\CalendarListResource::class, 'calendarList');
    }

    /**
     * The "calendars" resource.
     */
    public function calendars(): Calendar\CalendarsResource
    {
        return $this->resource(Calendar\CalendarsResource::class, 'calendars');
    }

    /**
     * The "channels" resource.
     */
    public function channels(): Calendar\ChannelsResource
    {
        return $this->resource(Calendar\ChannelsResource::class, 'channels');
    }

    /**
     * The "colors" resource.
     */
    public function colors(): Calendar\ColorsResource
    {
        return $this->resource(Calendar\ColorsResource::class, 'colors');
    }

    /**
     * The "events" resource.
     */
    public function events(): Calendar\EventsResource
    {
        return $this->resource(Calendar\EventsResource::class, 'events');
    }

    /**
     * The "freebusy" resource.
     */
    public function freebusy(): Calendar\FreebusyResource
    {
        return $this->resource(Calendar\FreebusyResource::class, 'freebusy');
    }

    /**
     * The "settings" resource.
     */
    public function settings(): Calendar\SettingsResource
    {
        return $this->resource(Calendar\SettingsResource::class, 'settings');
    }
}
