<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.

namespace BrickServers\GoogleWorkspace\Api;

/**
 * Every resource of the Google Classroom API (Google\Service\Classroom).
 */
class ClassroomApi extends ApiService
{
    /**
     * The "courses" resource.
     */
    public function courses(): Classroom\CoursesResource
    {
        return $this->resource(Classroom\CoursesResource::class, 'courses');
    }

    /**
     * The "courses_aliases" resource.
     */
    public function coursesAliases(): Classroom\CoursesAliasesResource
    {
        return $this->resource(Classroom\CoursesAliasesResource::class, 'courses_aliases');
    }

    /**
     * The "courses_announcements" resource.
     */
    public function coursesAnnouncements(): Classroom\CoursesAnnouncementsResource
    {
        return $this->resource(Classroom\CoursesAnnouncementsResource::class, 'courses_announcements');
    }

    /**
     * The "courses_announcements_addOnAttachments" resource.
     */
    public function coursesAnnouncementsAddOnAttachments(): Classroom\CoursesAnnouncementsAddOnAttachmentsResource
    {
        return $this->resource(Classroom\CoursesAnnouncementsAddOnAttachmentsResource::class, 'courses_announcements_addOnAttachments');
    }

    /**
     * The "courses_courseWork" resource.
     */
    public function coursesCourseWork(): Classroom\CoursesCourseWorkResource
    {
        return $this->resource(Classroom\CoursesCourseWorkResource::class, 'courses_courseWork');
    }

    /**
     * The "courses_courseWorkMaterials" resource.
     */
    public function coursesCourseWorkMaterials(): Classroom\CoursesCourseWorkMaterialsResource
    {
        return $this->resource(Classroom\CoursesCourseWorkMaterialsResource::class, 'courses_courseWorkMaterials');
    }

    /**
     * The "courses_courseWorkMaterials_addOnAttachments" resource.
     */
    public function coursesCourseWorkMaterialsAddOnAttachments(): Classroom\CoursesCourseWorkMaterialsAddOnAttachmentsResource
    {
        return $this->resource(Classroom\CoursesCourseWorkMaterialsAddOnAttachmentsResource::class, 'courses_courseWorkMaterials_addOnAttachments');
    }

    /**
     * The "courses_courseWork_addOnAttachments" resource.
     */
    public function coursesCourseWorkAddOnAttachments(): Classroom\CoursesCourseWorkAddOnAttachmentsResource
    {
        return $this->resource(Classroom\CoursesCourseWorkAddOnAttachmentsResource::class, 'courses_courseWork_addOnAttachments');
    }

    /**
     * The "courses_courseWork_addOnAttachments_studentSubmissions" resource.
     */
    public function coursesCourseWorkAddOnAttachmentsStudentSubmissions(): Classroom\CoursesCourseWorkAddOnAttachmentsStudentSubmissionsResource
    {
        return $this->resource(Classroom\CoursesCourseWorkAddOnAttachmentsStudentSubmissionsResource::class, 'courses_courseWork_addOnAttachments_studentSubmissions');
    }

    /**
     * The "courses_courseWork_rubrics" resource.
     */
    public function coursesCourseWorkRubrics(): Classroom\CoursesCourseWorkRubricsResource
    {
        return $this->resource(Classroom\CoursesCourseWorkRubricsResource::class, 'courses_courseWork_rubrics');
    }

    /**
     * The "courses_courseWork_studentSubmissions" resource.
     */
    public function coursesCourseWorkStudentSubmissions(): Classroom\CoursesCourseWorkStudentSubmissionsResource
    {
        return $this->resource(Classroom\CoursesCourseWorkStudentSubmissionsResource::class, 'courses_courseWork_studentSubmissions');
    }

    /**
     * The "courses_posts" resource.
     */
    public function coursesPosts(): Classroom\CoursesPostsResource
    {
        return $this->resource(Classroom\CoursesPostsResource::class, 'courses_posts');
    }

    /**
     * The "courses_posts_addOnAttachments" resource.
     */
    public function coursesPostsAddOnAttachments(): Classroom\CoursesPostsAddOnAttachmentsResource
    {
        return $this->resource(Classroom\CoursesPostsAddOnAttachmentsResource::class, 'courses_posts_addOnAttachments');
    }

    /**
     * The "courses_posts_addOnAttachments_studentSubmissions" resource.
     */
    public function coursesPostsAddOnAttachmentsStudentSubmissions(): Classroom\CoursesPostsAddOnAttachmentsStudentSubmissionsResource
    {
        return $this->resource(Classroom\CoursesPostsAddOnAttachmentsStudentSubmissionsResource::class, 'courses_posts_addOnAttachments_studentSubmissions');
    }

    /**
     * The "courses_studentGroups" resource.
     */
    public function coursesStudentGroups(): Classroom\CoursesStudentGroupsResource
    {
        return $this->resource(Classroom\CoursesStudentGroupsResource::class, 'courses_studentGroups');
    }

    /**
     * The "courses_studentGroups_studentGroupMembers" resource.
     */
    public function coursesStudentGroupsStudentGroupMembers(): Classroom\CoursesStudentGroupsStudentGroupMembersResource
    {
        return $this->resource(Classroom\CoursesStudentGroupsStudentGroupMembersResource::class, 'courses_studentGroups_studentGroupMembers');
    }

    /**
     * The "courses_students" resource.
     */
    public function coursesStudents(): Classroom\CoursesStudentsResource
    {
        return $this->resource(Classroom\CoursesStudentsResource::class, 'courses_students');
    }

    /**
     * The "courses_teachers" resource.
     */
    public function coursesTeachers(): Classroom\CoursesTeachersResource
    {
        return $this->resource(Classroom\CoursesTeachersResource::class, 'courses_teachers');
    }

    /**
     * The "courses_topics" resource.
     */
    public function coursesTopics(): Classroom\CoursesTopicsResource
    {
        return $this->resource(Classroom\CoursesTopicsResource::class, 'courses_topics');
    }

    /**
     * The "invitations" resource.
     */
    public function invitations(): Classroom\InvitationsResource
    {
        return $this->resource(Classroom\InvitationsResource::class, 'invitations');
    }

    /**
     * The "registrations" resource.
     */
    public function registrations(): Classroom\RegistrationsResource
    {
        return $this->resource(Classroom\RegistrationsResource::class, 'registrations');
    }

    /**
     * The "userProfiles" resource.
     */
    public function userProfiles(): Classroom\UserProfilesResource
    {
        return $this->resource(Classroom\UserProfilesResource::class, 'userProfiles');
    }

    /**
     * The "userProfiles_guardianInvitations" resource.
     */
    public function userProfilesGuardianInvitations(): Classroom\UserProfilesGuardianInvitationsResource
    {
        return $this->resource(Classroom\UserProfilesGuardianInvitationsResource::class, 'userProfiles_guardianInvitations');
    }

    /**
     * The "userProfiles_guardians" resource.
     */
    public function userProfilesGuardians(): Classroom\UserProfilesGuardiansResource
    {
        return $this->resource(Classroom\UserProfilesGuardiansResource::class, 'userProfiles_guardians');
    }
}
