<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.

namespace BrickServers\GoogleWorkspace\Api;

/**
 * Every resource of the Google Directory API (Google\Service\Directory).
 */
class DirectoryApi extends ApiService
{
    /**
     * The "asps" resource.
     */
    public function asps(): Directory\AspsResource
    {
        return $this->resource(Directory\AspsResource::class, 'asps');
    }

    /**
     * The "channels" resource.
     */
    public function channels(): Directory\ChannelsResource
    {
        return $this->resource(Directory\ChannelsResource::class, 'channels');
    }

    /**
     * The "chromeosdevices" resource.
     */
    public function chromeosdevices(): Directory\ChromeosdevicesResource
    {
        return $this->resource(Directory\ChromeosdevicesResource::class, 'chromeosdevices');
    }

    /**
     * The "customer_devices_chromeos" resource.
     */
    public function customerDevicesChromeos(): Directory\CustomerDevicesChromeosResource
    {
        return $this->resource(Directory\CustomerDevicesChromeosResource::class, 'customer_devices_chromeos');
    }

    /**
     * The "customer_devices_chromeos_commands" resource.
     */
    public function customerDevicesChromeosCommands(): Directory\CustomerDevicesChromeosCommandsResource
    {
        return $this->resource(Directory\CustomerDevicesChromeosCommandsResource::class, 'customer_devices_chromeos_commands');
    }

    /**
     * The "customers" resource.
     */
    public function customers(): Directory\CustomersResource
    {
        return $this->resource(Directory\CustomersResource::class, 'customers');
    }

    /**
     * The "customers_chrome_printServers" resource.
     */
    public function customersChromePrintServers(): Directory\CustomersChromePrintServersResource
    {
        return $this->resource(Directory\CustomersChromePrintServersResource::class, 'customers_chrome_printServers');
    }

    /**
     * The "customers_chrome_printers" resource.
     */
    public function customersChromePrinters(): Directory\CustomersChromePrintersResource
    {
        return $this->resource(Directory\CustomersChromePrintersResource::class, 'customers_chrome_printers');
    }

    /**
     * The "domainAliases" resource.
     */
    public function domainAliases(): Directory\DomainAliasesResource
    {
        return $this->resource(Directory\DomainAliasesResource::class, 'domainAliases');
    }

    /**
     * The "domains" resource.
     */
    public function domains(): Directory\DomainsResource
    {
        return $this->resource(Directory\DomainsResource::class, 'domains');
    }

    /**
     * The "groups" resource.
     */
    public function groups(): Directory\GroupsResource
    {
        return $this->resource(Directory\GroupsResource::class, 'groups');
    }

    /**
     * The "groups_aliases" resource.
     */
    public function groupsAliases(): Directory\GroupsAliasesResource
    {
        return $this->resource(Directory\GroupsAliasesResource::class, 'groups_aliases');
    }

    /**
     * The "members" resource.
     */
    public function members(): Directory\MembersResource
    {
        return $this->resource(Directory\MembersResource::class, 'members');
    }

    /**
     * The "mobiledevices" resource.
     */
    public function mobiledevices(): Directory\MobiledevicesResource
    {
        return $this->resource(Directory\MobiledevicesResource::class, 'mobiledevices');
    }

    /**
     * The "orgunits" resource.
     */
    public function orgunits(): Directory\OrgunitsResource
    {
        return $this->resource(Directory\OrgunitsResource::class, 'orgunits');
    }

    /**
     * The "privileges" resource.
     */
    public function privileges(): Directory\PrivilegesResource
    {
        return $this->resource(Directory\PrivilegesResource::class, 'privileges');
    }

    /**
     * The "resources_buildings" resource.
     */
    public function resourcesBuildings(): Directory\ResourcesBuildingsResource
    {
        return $this->resource(Directory\ResourcesBuildingsResource::class, 'resources_buildings');
    }

    /**
     * The "resources_calendars" resource.
     */
    public function resourcesCalendars(): Directory\ResourcesCalendarsResource
    {
        return $this->resource(Directory\ResourcesCalendarsResource::class, 'resources_calendars');
    }

    /**
     * The "resources_features" resource.
     */
    public function resourcesFeatures(): Directory\ResourcesFeaturesResource
    {
        return $this->resource(Directory\ResourcesFeaturesResource::class, 'resources_features');
    }

    /**
     * The "roleAssignments" resource.
     */
    public function roleAssignments(): Directory\RoleAssignmentsResource
    {
        return $this->resource(Directory\RoleAssignmentsResource::class, 'roleAssignments');
    }

    /**
     * The "roles" resource.
     */
    public function roles(): Directory\RolesResource
    {
        return $this->resource(Directory\RolesResource::class, 'roles');
    }

    /**
     * The "schemas" resource.
     */
    public function schemas(): Directory\SchemasResource
    {
        return $this->resource(Directory\SchemasResource::class, 'schemas');
    }

    /**
     * The "tokens" resource.
     */
    public function tokens(): Directory\TokensResource
    {
        return $this->resource(Directory\TokensResource::class, 'tokens');
    }

    /**
     * The "twoStepVerification" resource.
     */
    public function twoStepVerification(): Directory\TwoStepVerificationResource
    {
        return $this->resource(Directory\TwoStepVerificationResource::class, 'twoStepVerification');
    }

    /**
     * The "users" resource.
     */
    public function users(): Directory\UsersResource
    {
        return $this->resource(Directory\UsersResource::class, 'users');
    }

    /**
     * The "users_aliases" resource.
     */
    public function usersAliases(): Directory\UsersAliasesResource
    {
        return $this->resource(Directory\UsersAliasesResource::class, 'users_aliases');
    }

    /**
     * The "users_photos" resource.
     */
    public function usersPhotos(): Directory\UsersPhotosResource
    {
        return $this->resource(Directory\UsersPhotosResource::class, 'users_photos');
    }

    /**
     * The "verificationCodes" resource.
     */
    public function verificationCodes(): Directory\VerificationCodesResource
    {
        return $this->resource(Directory\VerificationCodesResource::class, 'verificationCodes');
    }
}
