<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.

namespace BrickServers\GoogleWorkspace\Api;

/**
 * Every resource of the Google Drive API (Google\Service\Drive).
 */
class DriveApi extends ApiService
{
    /**
     * The "about" resource.
     */
    public function about(): Drive\AboutResource
    {
        return $this->resource(Drive\AboutResource::class, 'about');
    }

    /**
     * The "accessproposals" resource.
     */
    public function accessproposals(): Drive\AccessproposalsResource
    {
        return $this->resource(Drive\AccessproposalsResource::class, 'accessproposals');
    }

    /**
     * The "approvals" resource.
     */
    public function approvals(): Drive\ApprovalsResource
    {
        return $this->resource(Drive\ApprovalsResource::class, 'approvals');
    }

    /**
     * The "apps" resource.
     */
    public function apps(): Drive\AppsResource
    {
        return $this->resource(Drive\AppsResource::class, 'apps');
    }

    /**
     * The "changes" resource.
     */
    public function changes(): Drive\ChangesResource
    {
        return $this->resource(Drive\ChangesResource::class, 'changes');
    }

    /**
     * The "channels" resource.
     */
    public function channels(): Drive\ChannelsResource
    {
        return $this->resource(Drive\ChannelsResource::class, 'channels');
    }

    /**
     * The "comments" resource.
     */
    public function comments(): Drive\CommentsResource
    {
        return $this->resource(Drive\CommentsResource::class, 'comments');
    }

    /**
     * The "drives" resource.
     */
    public function drives(): Drive\DrivesResource
    {
        return $this->resource(Drive\DrivesResource::class, 'drives');
    }

    /**
     * The "files" resource.
     */
    public function files(): Drive\FilesResource
    {
        return $this->resource(Drive\FilesResource::class, 'files');
    }

    /**
     * The "operations" resource.
     */
    public function operations(): Drive\OperationsResource
    {
        return $this->resource(Drive\OperationsResource::class, 'operations');
    }

    /**
     * The "permissions" resource.
     */
    public function permissions(): Drive\PermissionsResource
    {
        return $this->resource(Drive\PermissionsResource::class, 'permissions');
    }

    /**
     * The "replies" resource.
     */
    public function replies(): Drive\RepliesResource
    {
        return $this->resource(Drive\RepliesResource::class, 'replies');
    }

    /**
     * The "revisions" resource.
     */
    public function revisions(): Drive\RevisionsResource
    {
        return $this->resource(Drive\RevisionsResource::class, 'revisions');
    }

    /**
     * The "teamdrives" resource.
     */
    public function teamdrives(): Drive\TeamdrivesResource
    {
        return $this->resource(Drive\TeamdrivesResource::class, 'teamdrives');
    }
}
