<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.

namespace BrickServers\GoogleWorkspace\Api;

/**
 * Every resource of the Google Gmail API (Google\Service\Gmail).
 */
class GmailApi extends ApiService
{
    /**
     * The "users" resource.
     */
    public function users(): Gmail\UsersResource
    {
        return $this->resource(Gmail\UsersResource::class, 'users');
    }

    /**
     * The "users_drafts" resource.
     */
    public function usersDrafts(): Gmail\UsersDraftsResource
    {
        return $this->resource(Gmail\UsersDraftsResource::class, 'users_drafts');
    }

    /**
     * The "users_history" resource.
     */
    public function usersHistory(): Gmail\UsersHistoryResource
    {
        return $this->resource(Gmail\UsersHistoryResource::class, 'users_history');
    }

    /**
     * The "users_labels" resource.
     */
    public function usersLabels(): Gmail\UsersLabelsResource
    {
        return $this->resource(Gmail\UsersLabelsResource::class, 'users_labels');
    }

    /**
     * The "users_messages" resource.
     */
    public function usersMessages(): Gmail\UsersMessagesResource
    {
        return $this->resource(Gmail\UsersMessagesResource::class, 'users_messages');
    }

    /**
     * The "users_messages_attachments" resource.
     */
    public function usersMessagesAttachments(): Gmail\UsersMessagesAttachmentsResource
    {
        return $this->resource(Gmail\UsersMessagesAttachmentsResource::class, 'users_messages_attachments');
    }

    /**
     * The "users_settings" resource.
     */
    public function usersSettings(): Gmail\UsersSettingsResource
    {
        return $this->resource(Gmail\UsersSettingsResource::class, 'users_settings');
    }

    /**
     * The "users_settings_cse_identities" resource.
     */
    public function usersSettingsCseIdentities(): Gmail\UsersSettingsCseIdentitiesResource
    {
        return $this->resource(Gmail\UsersSettingsCseIdentitiesResource::class, 'users_settings_cse_identities');
    }

    /**
     * The "users_settings_cse_keypairs" resource.
     */
    public function usersSettingsCseKeypairs(): Gmail\UsersSettingsCseKeypairsResource
    {
        return $this->resource(Gmail\UsersSettingsCseKeypairsResource::class, 'users_settings_cse_keypairs');
    }

    /**
     * The "users_settings_delegates" resource.
     */
    public function usersSettingsDelegates(): Gmail\UsersSettingsDelegatesResource
    {
        return $this->resource(Gmail\UsersSettingsDelegatesResource::class, 'users_settings_delegates');
    }

    /**
     * The "users_settings_filters" resource.
     */
    public function usersSettingsFilters(): Gmail\UsersSettingsFiltersResource
    {
        return $this->resource(Gmail\UsersSettingsFiltersResource::class, 'users_settings_filters');
    }

    /**
     * The "users_settings_forwardingAddresses" resource.
     */
    public function usersSettingsForwardingAddresses(): Gmail\UsersSettingsForwardingAddressesResource
    {
        return $this->resource(Gmail\UsersSettingsForwardingAddressesResource::class, 'users_settings_forwardingAddresses');
    }

    /**
     * The "users_settings_sendAs" resource.
     */
    public function usersSettingsSendAs(): Gmail\UsersSettingsSendAsResource
    {
        return $this->resource(Gmail\UsersSettingsSendAsResource::class, 'users_settings_sendAs');
    }

    /**
     * The "users_settings_sendAs_smimeInfo" resource.
     */
    public function usersSettingsSendAsSmimeInfo(): Gmail\UsersSettingsSendAsSmimeInfoResource
    {
        return $this->resource(Gmail\UsersSettingsSendAsSmimeInfoResource::class, 'users_settings_sendAs_smimeInfo');
    }

    /**
     * The "users_threads" resource.
     */
    public function usersThreads(): Gmail\UsersThreadsResource
    {
        return $this->resource(Gmail\UsersThreadsResource::class, 'users_threads');
    }
}
