<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\ListHistoryResponse;

/**
 * Wraps Google\Service\Gmail\Resource\UsersHistory.
 */
class UsersHistoryResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'listUsersHistory' => 'GET',
    ];

    /**
     * Lists the history of all changes to the given mailbox. History results are
     * returned in chronological order (increasing `historyId`). For more
     * information, see [Synchronize clients with
     * Gmail](https://developers.google.com/workspace/gmail/api/guides/sync).
     * (history.listUsersHistory)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string historyTypes History types to be returned by the function
     * @opt_param string labelId Only return messages with a label matching the ID.
     * @opt_param string maxResults Maximum number of history records to return.
     * This field defaults to 100. The maximum allowed value for this field is 500.
     * @opt_param string pageToken Page token to retrieve a specific page of results
     * in the list.
     * @opt_param string startHistoryId Required. Returns history records after the
     * specified `startHistoryId`. The supplied `startHistoryId` should be obtained
     * from the `historyId` of a message, thread, or previous `list` response.
     * History IDs increase chronologically but are not contiguous with random gaps
     * in between valid IDs. Supplying an invalid or out of date `startHistoryId`
     * typically returns an `HTTP 404` error code. A `historyId` is typically valid
     * for at least a week, but in some rare circumstances may be valid for only a
     * few hours. If you receive an `HTTP 404` error response, your application
     * should perform a full sync. If you receive no `nextPageToken` in the
     * response, there are no updates to retrieve and you can store the returned
     * `historyId` for a future request.
     *
     * @return ListHistoryResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersHistory($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
