<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\Filter;
use Google\Service\Gmail\ListFiltersResponse;

/**
 * Wraps Google\Service\Gmail\Resource\UsersSettingsFilters.
 */
class UsersSettingsFiltersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersSettingsFilters' => 'GET',
    ];

    /**
     * Creates a filter. Note: you can only create a maximum of 1,000 filters. For
     * more information, see [Manage Gmail filters](https://developers.google.com/wo
     * rkspace/gmail/api/guides/filter_settings). (filters.create)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Filter
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, Filter $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Immediately and permanently deletes the specified filter. For more
     * information, see [Manage Gmail filters](https://developers.google.com/workspa
     * ce/gmail/api/guides/filter_settings). (filters.delete)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the filter to be deleted.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets a filter. For more information, see [Manage Gmail filters](https://devel
     * opers.google.com/workspace/gmail/api/guides/filter_settings). (filters.get)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the filter to be fetched.
     * @param  array  $optParams  Optional parameters.
     * @return Filter
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the message filters of a Gmail user. For more information, see [Manage
     * Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filte
     * r_settings). (filters.listUsersSettingsFilters)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return ListFiltersResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersSettingsFilters($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
