<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\CseKeyPair;
use Google\Service\Gmail\DisableCseKeyPairRequest;
use Google\Service\Gmail\EnableCseKeyPairRequest;
use Google\Service\Gmail\ListCseKeyPairsResponse;
use Google\Service\Gmail\ObliterateCseKeyPairRequest;

/**
 * Wraps Google\Service\Gmail\Resource\UsersSettingsCseKeypairs.
 */
class UsersSettingsCseKeypairsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'disable' => 'POST',
        'enable' => 'POST',
        'get' => 'GET',
        'listUsersSettingsCseKeypairs' => 'GET',
        'obliterate' => 'POST',
    ];

    /**
     * Creates and uploads a client-side encryption S/MIME public key certificate
     * chain and private key metadata for the authenticated user. For administrators
     * managing identities and keypairs for users in their organization, requests
     * require authorization with a [service account](https://developers.google.com/
     * identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation aut
     * hority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount
     * #delegatingauthority) to impersonate users with the
     * `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users
     * managing their own identities and keypairs, requests require [hardware key
     * encryption](https://support.google.com/a/answer/14153163) turned on and
     * configured. (keypairs.create)
     *
     * @param  string  $userId  The requester's primary email address. To indicate the
     *                          authenticated user, you can use the special value `me`.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string chainValidation The type of certificate chain validation to
     * perform at creation. The request will be rejected if the uploaded chain fails
     * to satisfy the requested validation checks. When unspecified, this parameter
     * defaults to `all`.
     *
     * @return CseKeyPair
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, CseKeyPair $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Turns off a client-side encryption key pair. The authenticated user can no
     * longer use the key pair to decrypt incoming CSE message texts or sign
     * outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the
     * key pair. After 30 days, you can permanently delete the key pair by using the
     * ObliterateCseKeyPair method. For administrators managing identities and
     * keypairs for users in their organization, requests require authorization with
     * a [service account](https://developers.google.com/identity/protocols/OAuth2Se
     * rviceAccount) that has [domain-wide delegation authority](https://developers.
     * google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to
     * impersonate users with the
     * `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users
     * managing their own identities and keypairs, requests require [hardware key
     * encryption](https://support.google.com/a/answer/14153163) turned on and
     * configured. (keypairs.disable)
     *
     * @param  string  $userId  The requester's primary email address. To indicate the
     *                          authenticated user, you can use the special value `me`.
     * @param  string  $keyPairId  The identifier of the key pair to turn off.
     * @param  array  $optParams  Optional parameters.
     * @return CseKeyPair
     *
     * @throws GoogleWorkspaceException
     */
    public function disable($userId, $keyPairId, DisableCseKeyPairRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Turns on a client-side encryption key pair that was turned off. The key pair
     * becomes active again for any associated client-side encryption identities.
     * For administrators managing identities and keypairs for users in their
     * organization, requests require authorization with a [service account](https:/
     * /developers.google.com/identity/protocols/OAuth2ServiceAccount) that has
     * [domain-wide delegation authority](https://developers.google.com/identity/pro
     * tocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with
     * the `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users
     * managing their own identities and keypairs, requests require [hardware key
     * encryption](https://support.google.com/a/answer/14153163) turned on and
     * configured. (keypairs.enable)
     *
     * @param  string  $userId  The requester's primary email address. To indicate the
     *                          authenticated user, you can use the special value `me`.
     * @param  string  $keyPairId  The identifier of the key pair to turn on.
     * @param  array  $optParams  Optional parameters.
     * @return CseKeyPair
     *
     * @throws GoogleWorkspaceException
     */
    public function enable($userId, $keyPairId, EnableCseKeyPairRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Retrieves an existing client-side encryption key pair. For administrators
     * managing identities and keypairs for users in their organization, requests
     * require authorization with a [service account](https://developers.google.com/
     * identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation aut
     * hority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount
     * #delegatingauthority) to impersonate users with the
     * `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users
     * managing their own identities and keypairs, requests require [hardware key
     * encryption](https://support.google.com/a/answer/14153163) turned on and
     * configured. (keypairs.get)
     *
     * @param  string  $userId  The requester's primary email address. To indicate the
     *                          authenticated user, you can use the special value `me`.
     * @param  string  $keyPairId  The identifier of the key pair to retrieve.
     * @param  array  $optParams  Optional parameters.
     * @return CseKeyPair
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $keyPairId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists client-side encryption key pairs for an authenticated user. For
     * administrators managing identities and keypairs for users in their
     * organization, requests require authorization with a [service account](https:/
     * /developers.google.com/identity/protocols/OAuth2ServiceAccount) that has
     * [domain-wide delegation authority](https://developers.google.com/identity/pro
     * tocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with
     * the `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users
     * managing their own identities and keypairs, requests require [hardware key
     * encryption](https://support.google.com/a/answer/14153163) turned on and
     * configured. (keypairs.listUsersSettingsCseKeypairs)
     *
     * @param  string  $userId  The requester's primary email address. To indicate the
     *                          authenticated user, you can use the special value `me`.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int pageSize The number of key pairs to return. If not provided,
     * the page size will default to 20 entries.
     * @opt_param string pageToken Pagination token indicating which page of key
     * pairs to return. If the token is not supplied, then the API will return the
     * first page of results.
     *
     * @return ListCseKeyPairsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersSettingsCseKeypairs($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a client-side encryption key pair permanently and immediately. You
     * can only permanently delete key pairs that have been turned off for more than
     * 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail
     * can't restore or decrypt any messages that were encrypted by an obliterated
     * key. Authenticated users and Google Workspace administrators lose access to
     * reading the encrypted messages. For administrators managing identities and
     * keypairs for users in their organization, requests require authorization with
     * a [service account](https://developers.google.com/identity/protocols/OAuth2Se
     * rviceAccount) that has [domain-wide delegation authority](https://developers.
     * google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to
     * impersonate users with the
     * `https://www.googleapis.com/auth/gmail.settings.basic` scope. For users
     * managing their own identities and keypairs, requests require [hardware key
     * encryption](https://support.google.com/a/answer/14153163) turned on and
     * configured. (keypairs.obliterate)
     *
     * @param  string  $userId  The requester's primary email address. To indicate the
     *                          authenticated user, you can use the special value `me`.
     * @param  string  $keyPairId  The identifier of the key pair to obliterate.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function obliterate($userId, $keyPairId, ObliterateCseKeyPairRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
