<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\Profile;
use Google\Service\Gmail\WatchRequest;
use Google\Service\Gmail\WatchResponse;

/**
 * Wraps Google\Service\Gmail\Resource\Users.
 */
class UsersResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'getProfile' => 'GET',
        'stop' => 'POST',
        'watch' => 'POST',
    ];

    /**
     * Gets the current user's Gmail profile. (users.getProfile)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Profile
     *
     * @throws GoogleWorkspaceException
     */
    public function getProfile($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Turn off push notification delivery for the given user mailbox. For more
     * information, see [Configure push notifications in Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/push).
     * (users.stop)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function stop($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Set up or update a push notification watch on the given user mailbox. For
     * more information, see [Configure push notifications in Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/push).
     * (users.watch)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return WatchResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function watch($userId, WatchRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
