<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\Draft;
use Google\Service\Gmail\ListDraftsResponse;
use Google\Service\Gmail\Message;

/**
 * Wraps Google\Service\Gmail\Resource\UsersDrafts.
 */
class UsersDraftsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersDrafts' => 'GET',
        'send' => 'POST',
        'update' => 'PUT',
    ];

    /**
     * Creates a draft with the `DRAFT` label. For more information, see [Create and
     * send draft
     * emails](https://developers.google.com/workspace/gmail/api/guides/drafts).
     * (drafts.create)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Draft
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, Draft $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Immediately and permanently deletes the specified draft. Does not simply
     * trash it. For more information, see [Create and send draft
     * emails](https://developers.google.com/workspace/gmail/api/guides/drafts).
     * (drafts.delete)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the draft to delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified draft. For more information, see [Create and send draft
     * emails](https://developers.google.com/workspace/gmail/api/guides/drafts).
     * (drafts.get)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the draft to retrieve.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string format The format to return the draft in.
     *
     * @return Draft
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the drafts in the user's mailbox. For more information, see [Create and
     * send draft
     * emails](https://developers.google.com/workspace/gmail/api/guides/drafts).
     * (drafts.listUsersDrafts)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeSpamTrash Include drafts from `SPAM` and `TRASH` in
     * the results.
     * @opt_param string maxResults Maximum number of drafts to return. This field
     * defaults to 100. The maximum allowed value for this field is 500.
     * @opt_param string pageToken Page token to retrieve a specific page of results
     * in the list.
     * @opt_param string q Only return draft messages matching the specified query.
     * Supports the same query format as the Gmail search box. For example,
     * `"from:someuser@example.com rfc822msgid: is:unread"`.
     *
     * @return ListDraftsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersDrafts($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Sends the specified, existing draft to the recipients in the `To`, `Cc`, and
     * `Bcc` headers. For more information, see [Create and send draft
     * emails](https://developers.google.com/workspace/gmail/api/guides/drafts).
     * (drafts.send)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function send($userId, Draft $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Replaces a draft's content. For more information, see [Create and send draft
     * emails](https://developers.google.com/workspace/gmail/api/guides/drafts).
     * (drafts.update)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the draft to update.
     * @param  array  $optParams  Optional parameters.
     * @return Draft
     *
     * @throws GoogleWorkspaceException
     */
    public function update($userId, $id, Draft $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
