<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\ForwardingAddress;
use Google\Service\Gmail\ListForwardingAddressesResponse;

/**
 * Wraps Google\Service\Gmail\Resource\UsersSettingsForwardingAddresses.
 */
class UsersSettingsForwardingAddressesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersSettingsForwardingAddresses' => 'GET',
    ];

    /**
     * Creates a forwarding address. If ownership verification is required, a
     * message will be sent to the recipient and the resource's verification status
     * will be set to `pending`; otherwise, the resource will be created with
     * verification status set to `accepted`. For more information, see [Manage
     * email forwarding](https://developers.google.com/workspace/gmail/api/guides/fo
     * rwarding_settings). This method is only available to service account clients
     * that have been delegated domain-wide authority. (forwardingAddresses.create)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return ForwardingAddress
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, ForwardingAddress $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes the specified forwarding address and revokes any verification that
     * may have been required. For more information, see [Manage email forwarding](h
     * ttps://developers.google.com/workspace/gmail/api/guides/forwarding_settings).
     * This method is only available to service account clients that have been
     * delegated domain-wide authority. (forwardingAddresses.delete)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $forwardingEmail  The forwarding address to be deleted.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $forwardingEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified forwarding address. For more information, see [Manage
     * email forwarding](https://developers.google.com/workspace/gmail/api/guides/fo
     * rwarding_settings). (forwardingAddresses.get)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $forwardingEmail  The forwarding address to be retrieved.
     * @param  array  $optParams  Optional parameters.
     * @return ForwardingAddress
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $forwardingEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the forwarding addresses for the specified account. For more
     * information, see [Manage email forwarding](https://developers.google.com/work
     * space/gmail/api/guides/forwarding_settings).
     * (forwardingAddresses.listUsersSettingsForwardingAddresses)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return ListForwardingAddressesResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersSettingsForwardingAddresses($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
