<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\Label;
use Google\Service\Gmail\ListLabelsResponse;

/**
 * Wraps Google\Service\Gmail\Resource\UsersLabels.
 */
class UsersLabelsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersLabels' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
    ];

    /**
     * Creates a label. For more information, see [Manage
     * labels](https://developers.google.com/workspace/gmail/api/guides/labels).
     * (labels.create)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Label
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, Label $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Immediately and permanently deletes the specified label and removes it from
     * any messages and threads that it's applied to. For more information, see
     * [Manage
     * labels](https://developers.google.com/workspace/gmail/api/guides/labels).
     * (labels.delete)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the label to delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified label. For more information, see [Manage
     * labels](https://developers.google.com/workspace/gmail/api/guides/labels).
     * (labels.get)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the label to retrieve.
     * @param  array  $optParams  Optional parameters.
     * @return Label
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists all labels in the user's mailbox. For more information, see [Manage
     * labels](https://developers.google.com/workspace/gmail/api/guides/labels).
     * (labels.listUsersLabels)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return ListLabelsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersLabels($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patch the specified label. For more information, see [Manage
     * labels](https://developers.google.com/workspace/gmail/api/guides/labels).
     * (labels.patch)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the label to update.
     * @param  array  $optParams  Optional parameters.
     * @return Label
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($userId, $id, Label $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates the specified label. For more information, see [Manage
     * labels](https://developers.google.com/workspace/gmail/api/guides/labels).
     * (labels.update)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the label to update.
     * @param  array  $optParams  Optional parameters.
     * @return Label
     *
     * @throws GoogleWorkspaceException
     */
    public function update($userId, $id, Label $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
