<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\BatchDeleteMessagesRequest;
use Google\Service\Gmail\BatchModifyMessagesRequest;
use Google\Service\Gmail\ListMessagesResponse;
use Google\Service\Gmail\Message;
use Google\Service\Gmail\ModifyMessageRequest;

/**
 * Wraps Google\Service\Gmail\Resource\UsersMessages.
 */
class UsersMessagesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'batchDelete' => 'POST',
        'batchModify' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'import' => 'POST',
        'insert' => 'POST',
        'listUsersMessages' => 'GET',
        'modify' => 'POST',
        'send' => 'POST',
        'trash' => 'POST',
        'untrash' => 'POST',
    ];

    /**
     * Deletes many messages by message ID. Provides no guarantees that messages
     * were not already deleted or even existed at all. (messages.batchDelete)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function batchDelete($userId, BatchDeleteMessagesRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Modifies the labels and the Classification Label values on the specified
     * messages. For administrators modifying messages for users in their
     * organization, requests require authorization with a [service account](https:/
     * /developers.google.com/identity/protocols/OAuth2ServiceAccount) that has
     * [domain-wide delegation authority](https://developers.google.com/identity/pro
     * tocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with
     * the `https://www.googleapis.com/auth/gmail.modify.restricted` scope.
     * (messages.batchModify)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function batchModify($userId, BatchModifyMessagesRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Immediately and permanently deletes the specified message. This operation
     * cannot be undone. Prefer `messages.trash` instead. (messages.delete)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the message to delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified message. (messages.get)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the message to retrieve. This ID is usually
     *                      retrieved using `messages.list`. The ID is also contained in the result when
     *                      a message is inserted (`messages.insert`) or imported (`messages.import`).
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string format The format to return the message in.
     * @opt_param string metadataHeaders When given and format is `METADATA`, only
     * include headers specified.
     *
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Imports a message into only this user's mailbox, with standard email delivery
     * scanning and classification similar to receiving via SMTP. This method
     * doesn't perform SPF checks, so it might not work for some spam messages, such
     * as those attempting to perform domain spoofing. This method does not send a
     * message. Note that the maximum size of the message is 150 MB.
     * (messages.import)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool deleted Mark the email as permanently deleted (not TRASH) and
     * only visible in Google Vault to a Vault administrator. Only used for Google
     * Workspace accounts.
     * @opt_param string internalDateSource Source for Gmail's internal date of the
     * message.
     * @opt_param bool neverMarkSpam Ignore the Gmail spam classifier decision and
     * never mark this email as SPAM in the mailbox.
     * @opt_param bool processForCalendar Process calendar invites in the email and
     * add any extracted meetings to the Google Calendar for this user.
     *
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function import($userId, Message $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Directly inserts a message into only this user's mailbox similar to `IMAP
     * APPEND`, bypassing most scanning and classification. Does not send a message.
     * For more information, see [Create and send email
     * messages](https://developers.google.com/workspace/gmail/api/guides/sending).
     * (messages.insert)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool deleted Mark the email as permanently deleted (not TRASH) and
     * only visible in Google Vault to a Vault administrator. Only used for Google
     * Workspace accounts.
     * @opt_param string internalDateSource Source for Gmail's internal date of the
     * message.
     *
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($userId, Message $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the messages in the user's mailbox. For more information, see [List
     * Gmail
     * messages](https://developers.google.com/workspace/gmail/api/guides/list-
     * messages). (messages.listUsersMessages)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeSpamTrash Include messages from `SPAM` and `TRASH` in
     * the results.
     * @opt_param string labelIds Only return messages with labels that match all of
     * the specified label IDs. Messages in a thread might have labels that other
     * messages in the same thread don't have. To learn more, see [Manage labels on
     * messages and threads](https://developers.google.com/workspace/gmail/api/guide
     * s/labels#manage_labels_on_messages_threads).
     * @opt_param string maxResults Maximum number of messages to return. This field
     * defaults to 100. The maximum allowed value for this field is 500.
     * @opt_param string pageToken Page token to retrieve a specific page of results
     * in the list.
     * @opt_param string q Only return messages matching the specified query.
     * Supports the same query format as the Gmail search box. For example,
     * `"from:someuser@example.com rfc822msgid: is:unread"`. Parameter cannot be
     * used when accessing the api using the gmail.metadata scope.
     *
     * @return ListMessagesResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersMessages($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Modifies the labels and the Classification Label values on the specified
     * message. For administrators modifying message for users in their
     * organization, requests require authorization with a [service account](https:/
     * /developers.google.com/identity/protocols/OAuth2ServiceAccount) that has
     * [domain-wide delegation authority](https://developers.google.com/identity/pro
     * tocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with
     * the `https://www.googleapis.com/auth/gmail.modify.restricted` scope.
     * (messages.modify)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the message to modify.
     * @param  array  $optParams  Optional parameters.
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function modify($userId, $id, ModifyMessageRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc`
     * headers. For more information, see [Create and send email
     * messages](https://developers.google.com/workspace/gmail/api/guides/sending).
     * (messages.send)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function send($userId, Message $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Moves the specified message to the trash. (messages.trash)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the message to Trash.
     * @param  array  $optParams  Optional parameters.
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function trash($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Removes the specified message from the trash. (messages.untrash)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the message to remove from Trash.
     * @param  array  $optParams  Optional parameters.
     * @return Message
     *
     * @throws GoogleWorkspaceException
     */
    public function untrash($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
