<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\ListThreadsResponse;
use Google\Service\Gmail\ModifyThreadRequest;
use Google\Service\Gmail\Thread;

/**
 * Wraps Google\Service\Gmail\Resource\UsersThreads.
 */
class UsersThreadsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersThreads' => 'GET',
        'modify' => 'POST',
        'trash' => 'POST',
        'untrash' => 'POST',
    ];

    /**
     * Immediately and permanently deletes the specified thread. Any messages that
     * belong to the thread are also deleted. This operation cannot be undone.
     * Prefer `threads.trash` instead. For more information, see [Manage
     * threads](https://developers.google.com/workspace/gmail/api/guides/threads).
     * (threads.delete)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  ID of the Thread to delete.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified thread. For more information, see [Manage
     * threads](https://developers.google.com/workspace/gmail/api/guides/threads).
     * (threads.get)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the thread to retrieve.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param string format The format to return the messages in.
     * @opt_param string metadataHeaders When given and format is METADATA, only
     * include headers specified.
     *
     * @return Thread
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the threads in the user's mailbox. For more information, see [Manage
     * threads](https://developers.google.com/workspace/gmail/api/guides/threads).
     * (threads.listUsersThreads)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool includeSpamTrash Include threads from `SPAM` and `TRASH` in
     * the results.
     * @opt_param string labelIds Only return threads with labels that match all of
     * the specified label IDs.
     * @opt_param string maxResults Maximum number of threads to return. This field
     * defaults to 100. The maximum allowed value for this field is 500.
     * @opt_param string pageToken Page token to retrieve a specific page of results
     * in the list.
     * @opt_param string q Only return threads matching the specified query.
     * Supports the same query format as the Gmail search box. For example,
     * `"from:someuser@example.com rfc822msgid: is:unread"`. Parameter cannot be
     * used when accessing the api using the gmail.metadata scope.
     *
     * @return ListThreadsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersThreads($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Modifies the labels applied to the thread. This applies to all messages in
     * the thread. For more information, see [Manage
     * threads](https://developers.google.com/workspace/gmail/api/guides/threads).
     * (threads.modify)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the thread to modify.
     * @param  array  $optParams  Optional parameters.
     * @return Thread
     *
     * @throws GoogleWorkspaceException
     */
    public function modify($userId, $id, ModifyThreadRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Moves the specified thread to the trash. Any messages that belong to the
     * thread are also moved to the trash. For more information, see [Manage
     * threads](https://developers.google.com/workspace/gmail/api/guides/threads).
     * (threads.trash)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the thread to Trash.
     * @param  array  $optParams  Optional parameters.
     * @return Thread
     *
     * @throws GoogleWorkspaceException
     */
    public function trash($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Removes the specified thread from the trash. Any messages that belong to the
     * thread are also removed from the trash. For more information, see [Manage
     * threads](https://developers.google.com/workspace/gmail/api/guides/threads).
     * (threads.untrash)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $id  The ID of the thread to remove from Trash.
     * @param  array  $optParams  Optional parameters.
     * @return Thread
     *
     * @throws GoogleWorkspaceException
     */
    public function untrash($userId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
