<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\ListSendAsResponse;
use Google\Service\Gmail\SendAs;

/**
 * Wraps Google\Service\Gmail\Resource\UsersSettingsSendAs.
 */
class UsersSettingsSendAsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersSettingsSendAs' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
        'verify' => 'POST',
    ];

    /**
     * Creates a custom "from" send-as alias. If an SMTP MSA is specified, Gmail
     * will attempt to connect to the SMTP service to validate the configuration
     * before creating the alias. If ownership verification is required for the
     * alias, a message will be sent to the email address and the resource's
     * verification status will be set to `pending`; otherwise, the resource will be
     * created with verification status set to `accepted`. If a signature is
     * provided, Gmail will sanitize the HTML before saving it with the alias. For
     * more information, see [Manage aliases and signatures with the Gmail API](http
     * s://developers.google.com/workspace/gmail/api/guides/alias_and_signature_sett
     * ings). This method is only available to service account clients that have
     * been delegated domain-wide authority. (sendAs.create)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return SendAs
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, SendAs $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes the specified send-as alias. Revokes any verification that may have
     * been required for using it. For more information, see [Manage aliases and
     * signatures with the Gmail API](https://developers.google.com/workspace/gmail/
     * api/guides/alias_and_signature_settings). This method is only available to
     * service account clients that have been delegated domain-wide authority.
     * (sendAs.delete)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The send-as alias to be deleted.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $sendAsEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified send-as alias. Fails with an HTTP 404 error if the
     * specified address is not a member of the collection. For more information,
     * see [Manage aliases and signatures with the Gmail API](https://developers.goo
     * gle.com/workspace/gmail/api/guides/alias_and_signature_settings).
     * (sendAs.get)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The send-as alias to be retrieved.
     * @param  array  $optParams  Optional parameters.
     * @return SendAs
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $sendAsEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the send-as aliases for the specified account. The result includes the
     * primary send-as address associated with the account as well as any custom
     * "from" aliases. For more information, see [Manage aliases and signatures with
     * the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias
     * _and_signature_settings). (sendAs.listUsersSettingsSendAs)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return ListSendAsResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersSettingsSendAs($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Patch the specified send-as alias. For more information, see [Manage aliases
     * and signatures with the Gmail API](https://developers.google.com/workspace/gm
     * ail/api/guides/alias_and_signature_settings). (sendAs.patch)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The send-as alias to be updated.
     * @param  array  $optParams  Optional parameters.
     * @return SendAs
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($userId, $sendAsEmail, SendAs $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates a send-as alias. If a signature is provided, Gmail will sanitize the
     * HTML before saving it with the alias. For more information, see [Manage
     * aliases and signatures with the Gmail API](https://developers.google.com/work
     * space/gmail/api/guides/alias_and_signature_settings). Addresses other than
     * the primary address for the account can only be updated by service account
     * clients that have been delegated domain-wide authority. (sendAs.update)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The send-as alias to be updated.
     * @param  array  $optParams  Optional parameters.
     * @return SendAs
     *
     * @throws GoogleWorkspaceException
     */
    public function update($userId, $sendAsEmail, SendAs $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Sends a verification email to the specified send-as alias address. The
     * verification status must be `pending`. For more information, see [Manage
     * aliases and signatures with the Gmail API](https://developers.google.com/work
     * space/gmail/api/guides/alias_and_signature_settings). This method is only
     * available to service account clients that have been delegated domain-wide
     * authority. (sendAs.verify)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The send-as alias to be verified.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function verify($userId, $sendAsEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
