<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\ListSmimeInfoResponse;
use Google\Service\Gmail\SmimeInfo;

/**
 * Wraps Google\Service\Gmail\Resource\UsersSettingsSendAsSmimeInfo.
 */
class UsersSettingsSendAsSmimeInfoResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listUsersSettingsSendAsSmimeInfo' => 'GET',
        'setDefault' => 'POST',
    ];

    /**
     * Deletes the specified S/MIME config for the specified send-as alias. For more
     * information, see [Manage S/MIME certificates with the Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).
     * (smimeInfo.delete)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The email address that appears in the "From:"
     *                               header for mail sent using this alias.
     * @param  string  $id  The immutable ID for the SmimeInfo.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $sendAsEmail, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified S/MIME config for the specified send-as alias. For more
     * information, see [Manage S/MIME certificates with the Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).
     * (smimeInfo.get)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The email address that appears in the "From:"
     *                               header for mail sent using this alias.
     * @param  string  $id  The immutable ID for the SmimeInfo.
     * @param  array  $optParams  Optional parameters.
     * @return SmimeInfo
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $sendAsEmail, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Insert (upload) the given S/MIME config for the specified send-as alias. Note
     * that `pkcs12` format is required for the key. For more information, see
     * [Manage S/MIME certificates with the Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).
     * (smimeInfo.insert)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The email address that appears in the "From:"
     *                               header for mail sent using this alias.
     * @param  array  $optParams  Optional parameters.
     * @return SmimeInfo
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($userId, $sendAsEmail, SmimeInfo $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists S/MIME configs for the specified send-as alias. For more information,
     * see [Manage S/MIME certificates with the Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).
     * (smimeInfo.listUsersSettingsSendAsSmimeInfo)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The email address that appears in the "From:"
     *                               header for mail sent using this alias.
     * @param  array  $optParams  Optional parameters.
     * @return ListSmimeInfoResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersSettingsSendAsSmimeInfo($userId, $sendAsEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Sets the default S/MIME config for the specified send-as alias. For more
     * information, see [Manage S/MIME certificates with the Gmail
     * API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).
     * (smimeInfo.setDefault)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $sendAsEmail  The email address that appears in the "From:"
     *                               header for mail sent using this alias.
     * @param  string  $id  The immutable ID for the SmimeInfo.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function setDefault($userId, $sendAsEmail, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
