<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\MessagePartBody;

/**
 * Wraps Google\Service\Gmail\Resource\UsersMessagesAttachments.
 */
class UsersMessagesAttachmentsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
    ];

    /**
     * Gets the specified message attachment. (attachments.get)
     *
     * @param  string  $userId  The user's email address. The special value `me` can be
     *                          used to indicate the authenticated user.
     * @param  string  $messageId  The ID of the message containing the attachment.
     * @param  string  $id  The ID of the attachment.
     * @param  array  $optParams  Optional parameters.
     * @return MessagePartBody
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $messageId, $id, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
