<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Gmail;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Gmail\Delegate;
use Google\Service\Gmail\ListDelegatesResponse;

/**
 * Wraps Google\Service\Gmail\Resource\UsersSettingsDelegates.
 */
class UsersSettingsDelegatesResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'create' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'listUsersSettingsDelegates' => 'GET',
    ];

    /**
     * Adds a delegate with its verification status set directly to `accepted`,
     * without sending any verification email. The delegate user must be a member of
     * the same Google Workspace organization as the delegator user. For more
     * information, see [Manage delegates](https://developers.google.com/workspace/g
     * mail/api/guides/delegate_settings). Gmail imposes limitations on the number
     * of delegates and delegators each user in a Google Workspace organization can
     * have. These limits depend on your organization, but in general each user can
     * have up to 25 delegates and up to 10 delegators. A delegate user must be
     * referred to by their primary email address, and not an email alias. When a
     * new delegate is created, there may be up to a one minute delay before the new
     * delegate is available for use. This method is only available to service
     * account clients that have been delegated domain-wide authority.
     * (delegates.create)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return Delegate
     *
     * @throws GoogleWorkspaceException
     */
    public function create($userId, Delegate $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Removes the specified delegate (which can be of any verification status), and
     * revokes any verification that may have been required for using it. For more
     * information, see [Manage delegates](https://developers.google.com/workspace/g
     * mail/api/guides/delegate_settings). A delegate user must be referred to by
     * their primary email address, and not an email alias. This method is only
     * available to service account clients that have been delegated domain-wide
     * authority. (delegates.delete)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $delegateEmail  The email address of the user to be removed as a
     *                                 delegate.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($userId, $delegateEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Gets the specified delegate. For more information, see [Manage delegates](htt
     * ps://developers.google.com/workspace/gmail/api/guides/delegate_settings). A
     * delegate user must be referred to by their primary email address, and not an
     * email alias. This method is only available to service account clients that
     * have been delegated domain-wide authority. (delegates.get)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  string  $delegateEmail  The email address of the user whose delegate
     *                                 relationship is to be retrieved.
     * @param  array  $optParams  Optional parameters.
     * @return Delegate
     *
     * @throws GoogleWorkspaceException
     */
    public function get($userId, $delegateEmail, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Lists the delegates for the specified account. For more information, see
     * [Manage delegates](https://developers.google.com/workspace/gmail/api/guides/d
     * elegate_settings). This method is only available to service account clients
     * that have been delegated domain-wide authority.
     * (delegates.listUsersSettingsDelegates)
     *
     * @param  string  $userId  User's email address. The special value "me" can be
     *                          used to indicate the authenticated user.
     * @param  array  $optParams  Optional parameters.
     * @return ListDelegatesResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function listUsersSettingsDelegates($userId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
