<?php

use Google\Client;
use Google\Service\Resource;

/**
 * Generates typed wrappers for every resource method of the supported Google APIs
 * from the installed google/apiclient-services package.
 *
 *   composer generate-api
 *
 * Output: src/Api/{Service}Api.php, src/Api/{Service}/*Resource.php and src/Api/manifest.php.
 * Re-run after updating google/apiclient-services to pick up new endpoints.
 */

require __DIR__.'/../vendor/autoload.php';

const SERVICES = [
    // Google service class => [wrapper name, service name used in logs/errors]
    'Directory' => ['Directory', 'directory'],
    'Classroom' => ['Classroom', 'classroom'],
    'Calendar' => ['Calendar', 'calendar'],
    'Gmail' => ['Gmail', 'gmail'],
    'Drive' => ['Drive', 'drive'],
];

const RESERVED = ['call', 'paginate', '__construct', 'items', 'identifier'];

$root = dirname(__DIR__);
$outDir = $root.'/src/Api';
$version = installedVersion($root, 'google/apiclient-services');
$manifest = ['version' => $version, 'services' => []];

foreach (SERVICES as $googleName => [$name, $serviceName]) {
    $serviceClass = "Google\\Service\\{$googleName}";
    $service = new $serviceClass(new Client);

    $resources = [];
    foreach ((new ReflectionObject($service))->getProperties(ReflectionProperty::IS_PUBLIC) as $property) {
        $value = $property->getValue($service);
        if (! $value instanceof Google\Service\Resource) {
            continue;
        }

        $methods = resourceMethods($value);
        if ($methods) {
            $resources[$property->getName()] = ['class' => get_class($value), 'methods' => $methods, 'object' => $value];
        }
    }
    ksort($resources);

    @mkdir("{$outDir}/{$name}", 0777, true);
    foreach (glob("{$outDir}/{$name}/*Resource.php") as $old) {
        unlink($old);
    }

    foreach ($resources as $property => $resource) {
        $class = shortName($resource['class']).'Resource';
        file_put_contents("{$outDir}/{$name}/{$class}.php", resourceFile($name, $class, $resource, $version));
        $manifest['services'][$serviceName][$property] = array_keys($resource['methods']);
    }

    file_put_contents("{$outDir}/{$name}Api.php", serviceFile($name, $serviceClass, $resources, $version));
    printf("%-10s %3d resources, %3d methods\n", $name, count($resources), array_sum(array_map(fn ($r) => count($r['methods']), $resources)));
}

file_put_contents("{$outDir}/manifest.php", "<?php\n\n// @generated by scripts/generate-api.php - do not edit\n\nreturn ".exportArray($manifest).";\n");

// ---------------------------------------------------------------------------

/**
 * Public API methods declared on a Google resource class, with their HTTP verb.
 *
 * @return array<string, array{reflection: ReflectionMethod, http: string}>
 */
function resourceMethods(Google\Service\Resource $resource): array
{
    $definitions = (new ReflectionProperty(Google\Service\Resource::class, 'methods'))->getValue($resource) ?? [];
    $class = new ReflectionClass($resource);
    $source = file($class->getFileName());
    $methods = [];

    foreach ($class->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
        if ($method->getDeclaringClass()->getName() !== $class->getName() || $method->isConstructor()) {
            continue;
        }
        if (in_array($method->getName(), RESERVED, true)) {
            throw new RuntimeException("{$class->getName()}::{$method->getName()} clashes with ApiResource");
        }

        // Each Google method body calls $this->call('<api method>', ...)
        $body = implode('', array_slice($source, $method->getStartLine() - 1, $method->getEndLine() - $method->getStartLine() + 1));
        if (! preg_match("/\\\$this->call\\('([^']+)'/", $body, $m) || ! isset($definitions[$m[1]]['httpMethod'])) {
            throw new RuntimeException("Cannot find the HTTP method of {$class->getName()}::{$method->getName()}");
        }

        $methods[$method->getName()] = ['reflection' => $method, 'http' => strtoupper($definitions[$m[1]]['httpMethod'])];
    }

    ksort($methods);

    return $methods;
}

function resourceFile(string $service, string $class, array $resource, string $version): string
{
    $imports = importsOf($resource['class']);
    $httpMethods = '';
    $methods = '';

    foreach ($resource['methods'] as $name => ['reflection' => $method, 'http' => $http]) {
        $httpMethods .= "        '{$name}' => '{$http}',\n";
        $methods .= "\n".docblock($method, $imports, $resource['class'])
            ."    public function {$name}(".parameters($method).")\n"
            ."    {\n"
            ."        return \$this->call(__FUNCTION__, func_get_args());\n"
            ."    }\n";
    }

    return <<<PHP
<?php

// @generated by scripts/generate-api.php from google/apiclient-services {$version} - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\\GoogleWorkspace\\Api\\{$service};

use BrickServers\\GoogleWorkspace\\Api\\ApiResource;

/**
 * Wraps {$resource['class']}.
 */
class {$class} extends ApiResource
{
    protected const HTTP_METHODS = [
{$httpMethods}    ];
{$methods}}

PHP;
}

function serviceFile(string $service, string $serviceClass, array $resources, string $version): string
{
    $accessors = '';
    foreach ($resources as $property => $resource) {
        $class = shortName($resource['class']).'Resource';
        $accessor = lcfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $property))));
        $accessors .= <<<PHP

    /**
     * The "{$property}" resource.
     */
    public function {$accessor}(): {$service}\\{$class}
    {
        return \$this->resource({$service}\\{$class}::class, '{$property}');
    }

PHP;
    }

    return <<<PHP
<?php

// @generated by scripts/generate-api.php from google/apiclient-services {$version} - do not edit.

namespace BrickServers\\GoogleWorkspace\\Api;

/**
 * Every resource of the Google {$service} API ({$serviceClass}).
 */
class {$service}Api extends ApiService
{{$accessors}}

PHP;
}

function parameters(ReflectionMethod $method): string
{
    $parts = [];
    foreach ($method->getParameters() as $param) {
        $type = '';
        if ($param->getType() instanceof ReflectionNamedType) {
            $t = $param->getType();
            $type = ($t->allowsNull() && $t->getName() !== 'mixed' ? '?' : '')
                .($t->isBuiltin() ? $t->getName() : '\\'.$t->getName()).' ';
        }
        $default = '';
        if ($param->isDefaultValueAvailable()) {
            $default = ' = '.exportArray($param->getDefaultValue());
        }
        $parts[] = $type.'$'.$param->getName().$default;
    }

    return implode(', ', $parts);
}

/**
 * Google's docblock, re-indented, with class names made fully qualified and
 * the thrown exception replaced by ours.
 */
function docblock(ReflectionMethod $method, array $imports, string $resourceClass): string
{
    $doc = $method->getDocComment() ?: "/**\n */";
    $namespace = substr($resourceClass, 0, strrpos($resourceClass, '\\Resource\\'));

    $lines = [];
    foreach (explode("\n", $doc) as $line) {
        $line = trim($line);
        if (str_starts_with($line, '* @throws')) {
            $line = '* @throws \\BrickServers\\GoogleWorkspace\\Exceptions\\GoogleWorkspaceException';
        }
        $line = preg_replace_callback('/^\* @(param|return) ([^\s$]+)/', function ($m) use ($imports, $namespace) {
            $types = array_map(fn ($t) => qualify($t, $imports, $namespace), explode('|', $m[2]));

            return "* @{$m[1]} ".implode('|', $types);
        }, $line);
        $lines[] = ($line === '/**' ? '    ' : '     ').$line;
    }

    // Methods Google documents without a return value (e.g. deletes) return an empty response
    if (! str_contains($doc, '@return')) {
        $throws = array_key_last(array_filter($lines, fn ($l) => str_contains($l, '@throws')));
        array_splice($lines, $throws ?? count($lines) - 1, 0, ['     * @return mixed']);
    }

    return implode("\n", $lines)."\n";
}

function qualify(string $type, array $imports, string $namespace): string
{
    $scalars = ['string', 'int', 'bool', 'float', 'array', 'mixed', 'object', 'null', 'callable', 'iterable', 'true', 'false', 'void', 'resource'];
    $base = rtrim($type, '[]');
    if ($base === '' || $base[0] === '\\' || in_array(strtolower($base), $scalars, true)) {
        return $type;
    }
    if (isset($imports[$base])) {
        return '\\'.$imports[$base].substr($type, strlen($base));
    }
    if (class_exists("{$namespace}\\{$base}")) {
        return "\\{$namespace}\\{$type}";
    }

    return $type;
}

/**
 * @return array<string, string> short name => fully qualified name
 */
function importsOf(string $class): array
{
    $imports = [];
    preg_match_all('/^use ([\w\\\\]+)(?: as (\w+))?;/m', file_get_contents((new ReflectionClass($class))->getFileName()), $matches, PREG_SET_ORDER);
    foreach ($matches as $m) {
        $imports[$m[2] ?? substr($m[1], strrpos($m[1], '\\') + 1)] = $m[1];
    }

    return $imports;
}

function shortName(string $class): string
{
    return substr($class, strrpos($class, '\\') + 1);
}

function exportArray(mixed $value, int $depth = 0): string
{
    if (! is_array($value)) {
        return var_export($value, true);
    }
    if ($value === []) {
        return '[]';
    }

    $pad = str_repeat('    ', $depth + 1);
    $list = array_is_list($value);
    $out = "[\n";
    foreach ($value as $k => $v) {
        $out .= $pad.($list ? '' : var_export($k, true).' => ').exportArray($v, $depth + 1).",\n";
    }

    return $out.str_repeat('    ', $depth).']';
}

function installedVersion(string $root, string $package): string
{
    foreach (json_decode(file_get_contents("{$root}/vendor/composer/installed.json"), true)['packages'] as $p) {
        if ($p['name'] === $package) {
            return ltrim($p['version'], 'v');
        }
    }

    throw new RuntimeException("{$package} is not installed");
}
