<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Calendar;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Calendar\Acl;
use Google\Service\Calendar\AclRule;
use Google\Service\Calendar\Channel;

/**
 * Wraps Google\Service\Calendar\Resource\Acl.
 */
class AclResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listAcl' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
        'watch' => 'POST',
    ];

    /**
     * Deletes an access control rule. (acl.delete)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  string  $ruleId  ACL rule identifier.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($calendarId, $ruleId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns an access control rule. (acl.get)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  string  $ruleId  ACL rule identifier.
     * @param  array  $optParams  Optional parameters.
     * @return AclRule
     *
     * @throws GoogleWorkspaceException
     */
    public function get($calendarId, $ruleId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates an access control rule. (acl.insert)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool sendNotifications Whether to send notifications about the
     * calendar sharing change. Optional. The default is True.
     *
     * @return AclRule
     *
     * @throws GoogleWorkspaceException
     */
    public function insert($calendarId, AclRule $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns the rules in the access control list for the calendar. (acl.listAcl)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of entries returned on one result
     * page. By default the value is 100 entries. The page size can never be larger
     * than 250 entries. Optional.
     * @opt_param string pageToken Token specifying which result page to return.
     * Optional.
     * @opt_param bool showDeleted Whether to include deleted ACLs in the result.
     * Deleted ACLs are represented by role equal to "none". Deleted ACLs will
     * always be included if syncToken is provided. Optional. The default is False.
     * @opt_param string syncToken Token obtained from the nextSyncToken field
     * returned on the last page of results from the previous list request. It makes
     * the result of this list request contain only entries that have changed since
     * then. All entries deleted since the previous list request will always be in
     * the result set and it is not allowed to set showDeleted to False. If the
     * syncToken expires, the server will respond with a 410 GONE response code and
     * the client should clear its storage and perform a full synchronization
     * without any syncToken. Learn more about incremental synchronization.
     * Optional. The default is to return all entries.
     *
     * @return Acl
     *
     * @throws GoogleWorkspaceException
     */
    public function listAcl($calendarId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates an access control rule. This method supports patch semantics.
     * (acl.patch)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  string  $ruleId  ACL rule identifier.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool sendNotifications Whether to send notifications about the
     * calendar sharing change. Note that there are no notifications on access
     * removal. Optional. The default is True.
     *
     * @return AclRule
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($calendarId, $ruleId, AclRule $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates an access control rule. (acl.update)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  string  $ruleId  ACL rule identifier.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool sendNotifications Whether to send notifications about the
     * calendar sharing change. Note that there are no notifications on access
     * removal. Optional. The default is True.
     *
     * @return AclRule
     *
     * @throws GoogleWorkspaceException
     */
    public function update($calendarId, $ruleId, AclRule $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Watch for changes to ACL resources. (acl.watch)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of entries returned on one result
     * page. By default the value is 100 entries. The page size can never be larger
     * than 250 entries. Optional.
     * @opt_param string pageToken Token specifying which result page to return.
     * Optional.
     * @opt_param bool showDeleted Whether to include deleted ACLs in the result.
     * Deleted ACLs are represented by role equal to "none". Deleted ACLs will
     * always be included if syncToken is provided. Optional. The default is False.
     * @opt_param string syncToken Token obtained from the nextSyncToken field
     * returned on the last page of results from the previous list request. It makes
     * the result of this list request contain only entries that have changed since
     * then. All entries deleted since the previous list request will always be in
     * the result set and it is not allowed to set showDeleted to False. If the
     * syncToken expires, the server will respond with a 410 GONE response code and
     * the client should clear its storage and perform a full synchronization
     * without any syncToken. Learn more about incremental synchronization.
     * Optional. The default is to return all entries.
     *
     * @return Channel
     *
     * @throws GoogleWorkspaceException
     */
    public function watch($calendarId, Channel $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
