<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Calendar;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Calendar\Calendar;

/**
 * Wraps Google\Service\Calendar\Resource\Calendars.
 */
class CalendarsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'clear' => 'POST',
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'patch' => 'PATCH',
        'transferOwnership' => 'POST',
        'update' => 'PUT',
    ];

    /**
     * Clears a primary calendar. This operation deletes all events associated with
     * the primary calendar of an account. (calendars.clear)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function clear($calendarId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Deletes a secondary calendar. Use calendars.clear for clearing all events on
     * primary calendars. (calendars.delete)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($calendarId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns metadata for a calendar. (calendars.get)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return Calendar
     *
     * @throws GoogleWorkspaceException
     */
    public function get($calendarId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Creates a secondary calendar. The authenticated user for the request is made
     * the data owner of the new calendar.
     *
     * Note: We recommend to authenticate as the intended data owner of the
     * calendar. You can use domain-wide delegation of authority to allow
     * applications to act on behalf of a specific user. Don't use a service account
     * for authentication. If you use a service account for authentication, the
     * service account is the data owner, which can lead to unexpected behavior. For
     * example, if a service account is the data owner, data ownership cannot be
     * transferred. (calendars.insert)
     *
     * @param  array  $optParams  Optional parameters.
     * @return Calendar
     *
     * @throws GoogleWorkspaceException
     */
    public function insert(Calendar $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates metadata for a calendar. This method supports patch semantics.
     * (calendars.patch)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return Calendar
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($calendarId, Calendar $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Transfers a secondary calendar between users within a Google Workspace
     * organization. Requires user authentication with Manage Calendars
     * administrator privilege, and one of the following authorization scopes: -
     * https://www.googleapis.com/auth/calendar  -
     * https://www.googleapis.com/auth/calendar.calendars In the request, set
     * useAdminAccess to true. The secondary calendar must be active to be
     * transferred. Transferring disabled or deleted calendars isn't supported.
     * (calendars.transferOwnership)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs, call
     *                              the calendarList.list method.
     * @param  string  $newDataOwner  The email address of a user who will become the
     *                                data owner of the calendar.
     * @param  bool  $useAdminAccess  When true, the method runs using the user's
     *                                Google Workspace administrator privileges. The calling user must be a Google
     *                                Workspace administrator with the Manage Calendars privilege. This method
     *                                currently only supports admin access, thus only true is accepted for this
     *                                field.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function transferOwnership($calendarId, $newDataOwner, $useAdminAccess, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates metadata for a calendar. (calendars.update)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return Calendar
     *
     * @throws GoogleWorkspaceException
     */
    public function update($calendarId, Calendar $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
