<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Calendar;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Calendar\CalendarList;
use Google\Service\Calendar\CalendarListEntry;
use Google\Service\Calendar\Channel;

/**
 * Wraps Google\Service\Calendar\Resource\CalendarList.
 */
class CalendarListResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'delete' => 'DELETE',
        'get' => 'GET',
        'insert' => 'POST',
        'listCalendarList' => 'GET',
        'patch' => 'PATCH',
        'update' => 'PUT',
        'watch' => 'POST',
    ];

    /**
     * Removes a calendar from the user's calendar list. (calendarList.delete)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return mixed
     *
     * @throws GoogleWorkspaceException
     */
    public function delete($calendarId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns a calendar from the user's calendar list. (calendarList.get)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     * @return CalendarListEntry
     *
     * @throws GoogleWorkspaceException
     */
    public function get($calendarId, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Inserts an existing calendar into the user's calendar list.
     * (calendarList.insert)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool colorRgbFormat Whether to use the foregroundColor and
     * backgroundColor fields to write the calendar colors (RGB). If this feature is
     * used, the index-based colorId field will be set to the best matching option
     * automatically. Optional. The default is False.
     *
     * @return CalendarListEntry
     *
     * @throws GoogleWorkspaceException
     */
    public function insert(CalendarListEntry $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns the calendars on the user's calendar list.
     * (calendarList.listCalendarList)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of entries returned on one result
     * page. By default the value is 100 entries. The page size can never be larger
     * than 250 entries. Optional.
     * @opt_param string minAccessRole The minimum access role for the user in the
     * returned entries. Optional. The default is no restriction.
     * @opt_param string pageToken Token specifying which result page to return.
     * Optional.
     * @opt_param bool showDeleted Whether to include deleted calendar list entries
     * in the result. Optional. The default is False.
     * @opt_param bool showHidden Whether to show hidden entries. Optional. The
     * default is False.
     * @opt_param bool showOwnOrganizationOnly Whether to show only entries for
     * calendars from the organization. This parameter is only applicable to Google
     * Workspace users. Optional. The default is False.
     * @opt_param string syncToken Token obtained from the nextSyncToken field
     * returned on the last page of results from the previous list request. It makes
     * the result of this list request contain only entries that have changed since
     * then. If only read-only fields such as calendar properties or ACLs have
     * changed, the entry won't be returned. All entries deleted and hidden since
     * the previous list request will always be in the result set and it is not
     * allowed to set showDeleted neither showHidden to False. To ensure client
     * state consistency minAccessRole and showOwnOrganizationOnly query parameters
     * cannot be specified together with nextSyncToken. If the syncToken expires,
     * the server will respond with a 410 GONE response code and the client should
     * clear its storage and perform a full synchronization without any syncToken.
     * Learn more about incremental synchronization. Optional. The default is to
     * return all entries.
     *
     * @return CalendarList
     *
     * @throws GoogleWorkspaceException
     */
    public function listCalendarList($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates an existing calendar on the user's calendar list. This method
     * supports patch semantics. (calendarList.patch)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool colorRgbFormat Whether to use the foregroundColor and
     * backgroundColor fields to write the calendar colors (RGB). If this feature is
     * used, the index-based colorId field will be set to the best matching option
     * automatically. Optional. The default is False.
     *
     * @return CalendarListEntry
     *
     * @throws GoogleWorkspaceException
     */
    public function patch($calendarId, CalendarListEntry $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Updates an existing calendar on the user's calendar list.
     * (calendarList.update)
     *
     * @param  string  $calendarId  Calendar identifier. To retrieve calendar IDs call
     *                              the calendarList.list method. If you want to access the primary calendar of
     *                              the currently logged in user, use the "primary" keyword.
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param bool colorRgbFormat Whether to use the foregroundColor and
     * backgroundColor fields to write the calendar colors (RGB). If this feature is
     * used, the index-based colorId field will be set to the best matching option
     * automatically. Optional. The default is False.
     *
     * @return CalendarListEntry
     *
     * @throws GoogleWorkspaceException
     */
    public function update($calendarId, CalendarListEntry $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Watch for changes to CalendarList resources. (calendarList.watch)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of entries returned on one result
     * page. By default the value is 100 entries. The page size can never be larger
     * than 250 entries. Optional.
     * @opt_param string minAccessRole The minimum access role for the user in the
     * returned entries. Optional. The default is no restriction.
     * @opt_param string pageToken Token specifying which result page to return.
     * Optional.
     * @opt_param bool showDeleted Whether to include deleted calendar list entries
     * in the result. Optional. The default is False.
     * @opt_param bool showHidden Whether to show hidden entries. Optional. The
     * default is False.
     * @opt_param bool showOwnOrganizationOnly Whether to show only entries for
     * calendars from the organization. This parameter is only applicable to Google
     * Workspace users. Optional. The default is False.
     * @opt_param string syncToken Token obtained from the nextSyncToken field
     * returned on the last page of results from the previous list request. It makes
     * the result of this list request contain only entries that have changed since
     * then. If only read-only fields such as calendar properties or ACLs have
     * changed, the entry won't be returned. All entries deleted and hidden since
     * the previous list request will always be in the result set and it is not
     * allowed to set showDeleted neither showHidden to False. To ensure client
     * state consistency minAccessRole and showOwnOrganizationOnly query parameters
     * cannot be specified together with nextSyncToken. If the syncToken expires,
     * the server will respond with a 410 GONE response code and the client should
     * clear its storage and perform a full synchronization without any syncToken.
     * Learn more about incremental synchronization. Optional. The default is to
     * return all entries.
     *
     * @return Channel
     *
     * @throws GoogleWorkspaceException
     */
    public function watch(Channel $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
