<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Calendar;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Calendar\Colors;

/**
 * Wraps Google\Service\Calendar\Resource\Colors.
 */
class ColorsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
    ];

    /**
     * Returns the color definitions for calendars and events. (colors.get)
     *
     * @param  array  $optParams  Optional parameters.
     * @return Colors
     *
     * @throws GoogleWorkspaceException
     */
    public function get($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
