<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Calendar;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Calendar\FreeBusyRequest;
use Google\Service\Calendar\FreeBusyResponse;

/**
 * Wraps Google\Service\Calendar\Resource\Freebusy.
 */
class FreebusyResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'query' => 'POST',
    ];

    /**
     * Returns free/busy information for a set of calendars. (freebusy.query)
     *
     * @param  array  $optParams  Optional parameters.
     * @return FreeBusyResponse
     *
     * @throws GoogleWorkspaceException
     */
    public function query(FreeBusyRequest $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
