<?php

// @generated by scripts/generate-api.php from google/apiclient-services 0.461.0 - do not edit.
// Method documentation is copied from google/apiclient-services (Apache License 2.0).

namespace BrickServers\GoogleWorkspace\Api\Calendar;

use BrickServers\GoogleWorkspace\Api\ApiResource;
use BrickServers\GoogleWorkspace\Exceptions\GoogleWorkspaceException;
use Google\Service\Calendar\Channel;
use Google\Service\Calendar\Setting;
use Google\Service\Calendar\Settings;

/**
 * Wraps Google\Service\Calendar\Resource\Settings.
 */
class SettingsResource extends ApiResource
{
    protected const HTTP_METHODS = [
        'get' => 'GET',
        'listSettings' => 'GET',
        'watch' => 'POST',
    ];

    /**
     * Returns a single user setting. (settings.get)
     *
     * @param  string  $setting  The id of the user setting.
     * @param  array  $optParams  Optional parameters.
     * @return Setting
     *
     * @throws GoogleWorkspaceException
     */
    public function get($setting, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Returns all user settings for the authenticated user. (settings.listSettings)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of entries returned on one result
     * page. By default the value is 100 entries. The page size can never be larger
     * than 250 entries. Optional.
     * @opt_param string pageToken Token specifying which result page to return.
     * Optional.
     * @opt_param string syncToken Token obtained from the nextSyncToken field
     * returned on the last page of results from the previous list request. It makes
     * the result of this list request contain only entries that have changed since
     * then. If the syncToken expires, the server will respond with a 410 GONE
     * response code and the client should clear its storage and perform a full
     * synchronization without any syncToken. Learn more about incremental
     * synchronization. Optional. The default is to return all entries.
     *
     * @return Settings
     *
     * @throws GoogleWorkspaceException
     */
    public function listSettings($optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }

    /**
     * Watch for changes to Settings resources. (settings.watch)
     *
     * @param  array  $optParams  Optional parameters.
     *
     * @opt_param int maxResults Maximum number of entries returned on one result
     * page. By default the value is 100 entries. The page size can never be larger
     * than 250 entries. Optional.
     * @opt_param string pageToken Token specifying which result page to return.
     * Optional.
     * @opt_param string syncToken Token obtained from the nextSyncToken field
     * returned on the last page of results from the previous list request. It makes
     * the result of this list request contain only entries that have changed since
     * then. If the syncToken expires, the server will respond with a 410 GONE
     * response code and the client should clear its storage and perform a full
     * synchronization without any syncToken. Learn more about incremental
     * synchronization. Optional. The default is to return all entries.
     *
     * @return Channel
     *
     * @throws GoogleWorkspaceException
     */
    public function watch(Channel $postBody, $optParams = [])
    {
        return $this->call(__FUNCTION__, func_get_args());
    }
}
